### ISSUE TITLE
No way to get back from add-on menu

### ISSUE THREAD

**Issue by briangunderson** [home-assistant/iOS#2256] opened 2022-11-20 17:18 UTC
**iOS device model, version and app version**

Model Name: iPhone 12 Pro Max
Software Version: 16.2
App version: 2022.10.1 (2022.424)

**Home Assistant Core Version**
 

2022.11.3

**Describe the bug**

User has no way to exit add-on page and must force quit app

**To Reproduce**

- Launch iOS HA app
- Navigate to add-ons 
- Select an add-on
- Attempt to get back to main HA menu (the back button simply loops between chosen add-on and list of add-ons)

**Expected behavior**

Back button should bring user to previous screen 

**Screenshots**

See video screen capture 
**Additional context**
https://user-images.githubusercontent.com/1896394/202916132-1593ea12-287e-415c-8eb5-27c04f068d3d.MOV

**Comment by 0pen5pace** [comment] 2022-11-23 07:25
I’m having the exact same behaviour. 
HA Core 2022.11.4
Iphone 12 Pro
IOS version 16.0 (20A362)

Currently the only solution I found: 
1. Put phone into flight mode or disconnect from wifi
2. Remove HA server
3. Reconnect to network 
4. Add server again
5. Now the overview screen will be shown again

Just to rule out any strange circumstances, I tried accessing an addon again through the addon menu. And I’m stuck again 😅

The issue is reproducible and major.

**Comment by 0pen5pace** [comment] 2022-11-23 07:34
I’m still new to Home Assistant and had just written a comment confirming the issue. Which I do. But you can retrieve the full menu by swiping from the left edge of your phone to the center. That way you can leave the loop. 

This seems to be more of a navigation concept issue rather then technical. 

I wasn’t aware of that feature and had first solved the issue by disconnecting the server when offline 😅

**Comment by Mariusthvdb** [comment] 2022-12-28 22:06
It's fixed with the new supervisor

**Closed** 2023-02-28 15:59 UTC
Labels: bug, ios
