### ISSUE TITLE
Significant delay in showing Streaming  Cameras, preview not working after app is idle

### ISSUE THREAD

**Issue by jazzmonger** [home-assistant/iOS#1309] opened 2020-12-22 02:01 UTC
**Device model, version and app version**

Model Name: 
macOS Version: 
<img width="266" alt="image" src="https://user-images.githubusercontent.com/52110065/102803305-e60be400-436c-11eb-8443-f818245c4dcf.png">

App Version: 2021.1 (1)
Safari Version: Version 13.1.3 (15609.4.1)

**Home Assistant Core Version**

Home Assistant 2020.12.1
**Describe the bug**
I have several cameras on the home screen.  Clicking on one in Safari produces and instant expanded live camera stream.
Doing the same in the MacOS app, there is a huge delay, 3-5 seconds at least, sometimes it never appears.  It happens on all camera feeds, and I have seveeral different cams, different resolution/manufacturers/etc, all the same result.

Also, when the app has been sitting idle for a while and I come back to it, none of the previews are available (this happens on IOS and MacOS.  it requires a hard refresh or terminate/restart in some cases to resume and see the camera previews.

**To Reproduce**
use any streaming camera

**Expected behavior**
instant view of selected camera
**Screenshots**

Normal screen
![image](https://user-images.githubusercontent.com/52110065/102804053-11430300-436e-11eb-8a95-4a816fa99af9.png)

Problem:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/52110065/102839930-83d7d100-43b6-11eb-9d35-9c9ec37cd807.png">

**Additional context**

**Comment by bgoncal** [comment] 2024-12-10 13:05
Can't reproduce, please let me know if this is still an issue for you.

Now Home Assistant uses WebRTC and unfotunately the webview from Mac Catalyst Apps (iOS Apps ported to mac) do not support it, so this can't be fixed on our side.

**Closed by bgoncal** 2024-12-10 13:05 UTC
Labels: bug, mac
