### ISSUE TITLE
Please make this a menu bar app 

### ISSUE THREAD

**Issue by koehntopp** [home-assistant/iOS#1304] opened 2020-12-18 17:03 UTC
**Is your feature request related to a problem? Please describe.**

This is a service I mainly require for the sensors, and I'd like to get rid of the window as well as the Application Menu Icon.

**Describe the solution you'd like**

Allow to run in "menu bar mode" with no other windows or icons on the desktoo unless triggered from the menu bar.

**Additional context**

**Comment by SeanPM5** [comment] 2020-12-18 17:12
Duplicate of https://github.com/home-assistant/iOS/issues/949, you can add a thumbs up to that feature request to show your interest :) 

Thanks.

**Closed by SeanPM5** 2020-12-18 17:12 UTC
Labels: feature-request, mac
