### ISSUE TITLE
gauge card does not display correctly

### ISSUE THREAD

**Issue by magnus919** [home-assistant/iOS#2054] opened 2022-01-29 22:36 UTC
**iOS device model, version and app version**

Model Name: iPhone 13 Pro
Software Version: 15.2.1
App version: 2021.327

**Home Assistant Core Version**

2021.12.10

**Describe the bug**
The filled area for the gauge card is shifted away from the area that it should be filling.

**To Reproduce**
Go to Energy module, scroll down to "Non-fossil energy consumed".

**Expected behavior**
Gauge card will fill correctly based on value of the sensor it is representing.

**Screenshots**

https://imgur.com/TZI7baX

**Additional context**

**Comment by TomBrien** [comment] 2022-01-29 22:40
Hi. This is a duplicate of #2038 and is fixed in 2021.2 (see https://github.com/home-assistant/frontend/issues/11041)

**Closed** 2022-01-29 22:40 UTC
Labels: bug, ios
