### ISSUE TITLE
MacOS History Log Doesn't Show Up under Big Sur Beta 7 or 8

### ISSUE THREAD

**Issue by bkvargyas** [home-assistant/iOS#1083] opened 2020-09-23 20:01 UTC
**Device model, version and app version**

Model Name: 
Software Version: Big Sur V11.0 Beta 20A5374i
App version: 2020.7(2)

**Home Assistant Core Version**

0.115.2

**Describe the bug**
History Log doesn't show up. - Doesn't work under IOS 14 Home Assistant App either --- but does work with Safari, although slower then Chrome or Edge on both MacOS and IOS

**To Reproduce**
Run the application, connect to Home Assistant, Select History Log

**Expected behavior**
Standard History Log to Show

**Screenshots**

![image](https://user-images.githubusercontent.com/8314737/94063096-3941bb00-fdad-11ea-906c-42c805469ec9.png)

**Additional context**

**Comment by TomBrien** [comment] 2020-09-23 20:36
If you scroll down (a lot!) is it there? I see the same thing but the log is there just with a huge padding at the top

**Comment by bkvargyas** [comment] 2020-09-23 21:30
Tom,

So you are correct, here is another snapshot of the scroll to the bottom:
You should note that if you place the mouse over the white space, the names of the history items show up, they just are not rendering correctly.    I'm guessing it's an issue with WebKit, and from what I've seen, even Safari under Big Sur, while it will eventually render it, takes 2-3 times as long as Chrome or Edge(chrome) does --- which is not normal for Safari.

![image](https://user-images.githubusercontent.com/8314737/94071579-c559df80-fdb9-11ea-8fe3-67efcca4db73.png)

**Comment by bkvargyas** [comment] 2020-09-23 21:34
Here is what Safari Does during initial rendering -- After 5 seconds, it shows normally.   This is on a 16" macbook pro, i9 processor --- clearly an issue.
![image](https://user-images.githubusercontent.com/8314737/94072011-81b3a580-fdba-11ea-96bf-484398878c12.png)

**Comment by TomBrien** [comment] 2020-09-23 21:36
So in Safari on iOS I see exactly the same behaviour. It's all the timeline plots that are missing. I think this is most likely a frontend issue as the behaviour in safari on iOS is the same. I wonder if someone from @home-assistant/frontend could have a quick look. We can move this over there if confirmed.

**Comment by bdraco** [comment] 2020-09-23 22:52
This is a dupe of https://github.com/home-assistant/frontend/issues/3340

**Comment by SeanPM5** [comment] 2020-09-23 23:40
Closing in favor of the above frontend issue

**Closed by SeanPM5** 2020-09-23 23:40 UTC
Labels: bug, mac
