### ISSUE TITLE
Copy/Paste function does not work at all on macOS app!

### ISSUE THREAD

**Issue by jonathanalevi** [home-assistant/iOS#2299] opened 2023-02-04 14:41 UTC
**Device model, version and app version**

Model Name: MacBook Pro M1 Max
macOS Version: MacOS 13.1 
App Version: 2022.10.1 (2022.424)
Safari Version: Version 16.2 (18614.3.7.1.5)

**Home Assistant Core Version**
2023.2.0

**Describe the bug**
When trying to edit YAML in osX (automations), it doesn't work. Unable to copy or paste. Cut works, but I can't paste. Copy/Cut don't seem to actually put it on the mac's keyboard, either, when I check a keyboard history app. 

**To Reproduce**
Edit an automation in YAML. 

**Expected behavior**
Copy/paste should work

**Comment by TomBrien** [comment] 2023-02-04 22:24
This is a duplicate of #1154 (along with some others). I'm closing this as updates are given there.

**Closed** 2023-02-04 22:28 UTC
Labels: bug, mac
