### ISSUE TITLE
2024.7: watchOS action background color removal issues (icons, system colors, etc.)

### ISSUE THREAD

**Issue by felixmueller** [home-assistant/iOS#2875] opened 2024-07-26 08:31 UTC
Model Name: Apple Watch
Software Version: 10.5
App version: 2024.7

**Home Assistant Core Version**
2024.7.3

**Describe the bug**
watchOS action background color was removed in this release (deprecated before). As a result, all items are now displayed in white (not matching the watchOS default item color, which is grey). All icons set to white are now invisible. The bright white color looks kind of ugly and does not match the watchOS default system color.

**To Reproduce**
Update to 2024.7, add an action with white icon, open watchOS App.

**Expected behavior**
The color selection seems to have been removed without any replacement. I would expect what the items then at least match the system default color to look familiar to other Apps (like settings for example).

**Screenshots**
Old look:
<img src="https://github.com/user-attachments/assets/0016132a-7549-4340-a397-8d785c77e5a1" width="500">
New look:
<img src="https://github.com/user-attachments/assets/c5ea5de0-c210-4c83-9d7e-89101e8660e8" width="500">
watchOS default look:
<img src="https://github.com/user-attachments/assets/f27371d8-25f5-449f-8861-32d54f05d6cd" width="500">

**Comment by henriklund** [comment] 2024-07-27 20:56
The change to only allow white background actually requires one to read the text of all actions instead of orientation by colours. This actually makes a difference for those who do not have 20/20 vision at every occasion

**Comment by bgoncal** [comment] 2024-07-27 21:21
Thanks for the feedback, I’ll discuss with the designers.

**Comment by AdriEU** [comment] 2024-07-29 06:09
+1

**Comment by HealsCodes** [comment] 2024-07-29 10:24
+1 

The old design was a lot easier to use without glasses as you could simply identify the buttons by their colour.

If the new 'badge' style icons are a conscious design decision I would like to suggest not change the button backgrounds to a dark grey like the rest of watchOS has by default.

The current white buttons are nearly blinding and very hard to read if you use your watch at night.

**Comment by bgoncal** [comment] 2024-07-29 10:39
https://github.com/home-assistant/iOS/pull/2880

**Comment by bgoncal** [comment] 2024-07-29 10:41
Closing this issue since it is not a bug and was an intentional change.

**Closed by bgoncal** 2024-07-29 10:41 UTC
Labels: enhancement, ios

**Comment by HealsCodes** [comment] 2024-07-29 11:04
You PR seems to address all of the issues mentioned here, thank you 😁

**Comment by fake-name** [comment] 2024-08-06 07:46
> Closing this issue since it is not a bug and was an intentional change.

That means it's an _intentional bug_.  This was, in any event, a massive step backwards in usability, and is still a bug.

**Comment by bgoncal** [comment] 2024-08-06 07:54
@fake-name thanks for your feedback :)

**Comment by tuiliere** [comment] 2024-08-08 08:41
Best user experience would be :
1. A global setting to set all actions text/back/icon colors in one place, which, by default, could be aligned to the curent theme setting or any other default values that appears appropriate.
2. Possibility to overload these global settings for each action independently.

**Comment by biscuitee** [comment] 2024-08-14 22:24
+1 
needed the background color and text color back as I am not able to see the text without glasses at night on bed

**Comment by HealsCodes** [comment] 2024-08-15 06:39
> +1 
> 
> needed the background color and text color back as I am not able to see the text without glasses at night on bed 

Did you actually see that they are already back in the linked commits/PR before the issue was closed? 

There just hasn't been a new release yet.

**Comment by bgoncal** [comment] 2024-08-15 11:11
> > +1
> > needed the background color and text color back as I am not able to see the text without glasses at night on bed
> 
> Did you actually see that they are already back in the linked commits/PR before the issue was closed?
> 
> There just hasn't been a new release yet.

It currently available in testflight build and it will be released to the App Store in the end of the month, feel free to try it out the beta if you want.

**Comment by marcgarciamarti** [comment] 2024-08-20 19:11
> > Closing this issue since it is not a bug and was an intentional change.
> 
> That means it's an _intentional bug_. This was, in any event, a massive step backwards in usability, and is still a bug.
> 
> If you do something wrong on purpose, it is still wrong.
> 
> > will be opt-in, by default
> 
> It should default to the way it previously worked. The new, much worse presentation should be the thing that is opt in.

check this out: https://github.com/home-assistant/iOS/issues/2921#issuecomment-2299574020
