### ISSUE TITLE
Audio output and microphone not detected when using Bluetooth earphones

### ISSUE THREAD

**Issue by parautenbach** [home-assistant/iOS#2166] opened 2022-07-31 19:37 UTC
**Device model, version and app version**

Model Name: iMac (24-inch, M1, 2021)
macOS Version: 12.4 (Monterey)
App Version: 2022.3 (358)
Safari Version: Version 15.5 (17613.2.7.1.8)

**Home Assistant Core Version**
2022.7.6

**Describe the bug**

The binary sensors for audio output and microphone changes to off when Bluetooth earphones (e.g. Apple Airpods) are connected while being in an online call (e.g. Google Meet). 

``` 
active: {{ states('binary_sensor.gaia_active') }}
app: {{ states('sensor.gaia_frontmost_app') }}
audio output in use: {{ states('binary_sensor.gaia_audio_output_in_use') }}
camera in use: {{ states('binary_sensor.gaia_camera_in_use') }}
mic in use: {{ states('binary_sensor.gaia_microphone_in_use') }}
active audio output: {{ states('sensor.gaia_active_audio_output') }}
active camera: {{ states('sensor.gaia_active_camera') }}
active mic: {{ states('sensor.gaia_active_microphone') }}
```

**To Reproduce**

Dial into an online call using a Mac and connect Bluetooth earphones. 

**Expected behavior**

Binary sensors to reflect the true state of the audio output and microphone. 

**Screenshots**

Using the built-in audio devices:
<img width="310" alt="Screenshot 2022-07-31 at 21 34 46" src="https://user-images.githubusercontent.com/743320/182042353-d7949f8b-f35d-46b1-9b5e-b1f1e200fcfc.png">

Using Apple Airpods:
<img width="297" alt="Screenshot 2022-07-31 at 21 35 01" src="https://user-images.githubusercontent.com/743320/182042368-e943a308-fe07-4bf2-97ca-589f9771d8fa.png">

**Comment by benjaminreede** [comment] 2022-08-04 07:31
Have the same issue, also with Monterey 12.4. Can't remember if it worked before in Monterey. Probably duplicate of #1903

**Comment by parautenbach** [comment] 2022-08-04 10:57
Thanks for picking up on this. I've subscribed to the other issue. I couldn't find it before I logged this.

**Closed** 2022-08-04 10:59 UTC
Labels: bug, mac
