### ISSUE TITLE
Apple Watch triggered actions fails under iOS 14

### ISSUE THREAD

**Issue by Nicxe** [home-assistant/iOS#907] opened 2020-08-15 12:21 UTC
iPhone 11  with iOs 14 public beta (A2221)
Apple Watch Series 5 with watchOs 6.2.8 (A2093)

Model Name: iPhone 11 (A2221)
Software Version: ios 14, Public beta
App version: Companion 2020.5.2

Model Name: AppleWatch Series 5 (A2093)
Software Version: watchOs 6.2.8
App version: Companion 2020.5.2

Running Home Assitant 0.114.0

I cant trigger an action I the companion app on my apple watch when the app is in the background and phone is locked. Nothing happens. It works fine when I have the phone unlocked and the app opened. I can't find anything in any log when I try to trigger the action and nothing happens.

It works the first 30 seconds after I close the app, but then it stops. 
If I try to trigger an action when I open the app on the watch nothing happens, then I wait 10 sec and try the same action again it often works.

So open the app in the watch and try to trigger a couple of times often works, and then I can trigger all action in the app until I close the phone again. 

I don't relay know if I can find anything in other logs, please let me know if I can provide with more info and how I can find it then.

**Comment by isabellaalstrom** [comment] 2020-08-16 08:23
Same issue here.

**Comment by TomBrien** [comment] 2020-08-16 10:19
I do not, currently, see this with WatchOS 7/iOS 14 both at dev beta 4 and Home Assistant 0.114.1 and app 2020.6(1) or 2020.5. However, this is something I have seen a lot and Zac and I spent quite a while trying to debug. The underlying cause, we believed was iOS's throttling of background processes. A quick test for this is when an action doesn't work, if you open the app on your phone it should immediately fire the action. The more you use the phone app, this should train iOS into allowing the app to do more in the background. I have also seen that if the action fired from Watch doesn't work immediately, it often fires a minute or too later (clearly to long a delay to be useful). This has actually been a problem I have seen intermittently since 2019.1 so I do think it's an iOS thing.

**Comment by Nicxe** [comment] 2020-08-17 08:53
I tested to open the app and it will not fire the action at all, nothing happens. I have also tried to wait a couple of minutes but it will not fire. It´s very clear when it´s not working because I do not get this "second" haptic feedback on the watch. I always get the first when I press the action but not the second that it have fired. 

I didn't have this issue on ios13, but perhaps the app resets its learning when I updated it to io14. I have yet noticed any improvement, it still works as described but maybe it´s too short of time for the app to learn and improve.

**Comment by TomBrien** [comment] 2020-08-17 09:11
Are you able to put the WatchOS beta on your watch? I'm wondering if there is some issue with the combination of WatchOS 6 and the iOS 14 beta.

**Comment by Nicxe** [comment] 2020-08-17 10:27
I don't really want to do that yes, I am relying on it for the hart thing and sends that to my doctor. However, I think that @isabellaalstrom which has the same issue is running the beta on her watch.

**Comment by TomBrien** [comment] 2020-08-21 08:47
Ok I can reproduce this now and I'm pretty certain #822 is the root cause. Every time I get a pop up saying the app has crashed, my actions stop working until I re open the app. I k ow Realm are looking at that issue. Hopefully we'll have a fix soon 🤞

**Comment by TomBrien** [comment] 2020-08-27 07:45
I should just mention that the dependency causing the background crash (realm) has had a potential fix merged so hopefully that will be available to us soon. Also, using the [TestFlight beta](http://home-assistant.io/ios/beta) will allow you to opt in to a partial mitigation to the crash. This works for me 95 % of the time.

**Comment by TomBrien** [comment] 2020-09-03 13:52
With #980 being fixed in 2020.6(11) this should be fixed now. I certainly don't see it anymore. If anyone still sees this in 2020.6(11) please post back here and reopen :)

**Closed by TomBrien** 2020-09-03 13:52 UTC
Labels: 2020.5, bug, iOS 14, watch
