### ISSUE TITLE
It appears the app has been taken off the app store?

### ISSUE THREAD

**Issue by ScribbleNerd** [home-assistant/iOS#601] opened 2020-06-07 01:31 UTC
**iOS device model, version and app version**

Model Name: iPhone SE 2016, iPhone X & macOS 10.13
Software Version: iOS 13.5
App version: N/A

**Home Assistant Core Version**
0.110.5

**Describe the bug**
When clicking on the link for the app on the Home Assistant website, it says "App Not Available This app is currently not available in ytour country or region."
I was able to install the app on my phone about a day ago, but now when going to the app store on any device, it shows that error

**To Reproduce**
Go to any link for the Home Assistant app in Safari (in chrome for iOS it just pops up with a white screen).

**Expected behavior**
I'm able to download the app like I was about a day ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/31575858/83958186-89176900-a834-11ea-8960-8690dbc90d56.png)
![image](https://user-images.githubusercontent.com/31575858/83958197-ad734580-a834-11ea-8c4e-72a9a212714e.png)

**Comment by ScribbleNerd** [comment] 2020-06-07 01:35
Looked in another GitHub Issue and found this: https://twitter.com/Robbie/status/1268822295151169537

**Comment by TomBrien** [comment] 2020-06-07 06:53
This is a duplicate of #598. Closing in favour of that issue

**Closed** 2020-06-07 06:53 UTC
Labels: duplicate
