### ISSUE TITLE
macOS onboarding failure when connected to proxy

### ISSUE THREAD

**Issue by ntompson** [home-assistant/iOS#1064] opened 2020-09-21 01:27 UTC
**Device model, version and app version**

Model Name: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Software Version: Catalina 10.15.6
App version: 2020.7 (2)

**Home Assistant Core Version**

HA version: 0.114.4

**Describe the bug**
When running the macOS app for the first time, my HA instance is found, and the login process begins, but after entering correct user name and password, I get a failure message when moving to the TFA provider selection screen. This loops repeatedly - sometimes the TFA login screen is displayed. Sometimes it is not. Sometimes the error is "This webpage was reloaded because a problem occurred.", other times a grey screen with "A problem repeatedly occurred..." message.

I'm connected to my corporate VPN, which isolates me from my LAN and proxies internet connections.

**To Reproduce**
Start macOS HA app for first time while connected to internet via proxy. Proceed through instance auto-detect, click "Connect" on Authentication screen. Enter username and password. Possibly make TFA provider selection. Receive error.

**Expected behavior**
Login completes and onboarding process continues.

**Screenshots**

<img width="583" alt="Screen Shot 2020-09-21 at 11 13 28 am" src="https://user-images.githubusercontent.com/32885870/93726931-06a49080-fbfc-11ea-9326-4257f4093636.png">

<img width="582" alt="Screen Shot 2020-09-21 at 11 16 16 am" src="https://user-images.githubusercontent.com/32885870/93726934-086e5400-fbfc-11ea-803c-0c03f0139e0b.png">

**Additional context**

I am able to connect to my HA instance through Safari, Chrome and a Chrome app while connected to corporate VPN / internet proxy. I can both onboard and use all functionality by these methods. It seems to only be the new macOS app that is impacted. 

I have also disconnected from the corporate VPN and still get this error, so it could be that the proxy is unrelated. However, I have successfully onboarded on another Mac (MacBook Pro 16"), which is not connected to the corporate VPN. I also find that the corporate VPN is not very good at cleaning up after itself, so it could be that I can onboard after a restart (not connected to the corporate VPN) - I haven't tried this.

**Comment by zacwest** [comment] 2020-09-21 01:45
Do you have Safari 14 installed? You may need to update to HA 0.115 for the buttons to work - Apple shipped a regression (which happened in iOS 14 but was fixed before release) which makes many buttons cause the page to reload/crash.

**Comment by ntompson** [comment] 2020-09-21 01:59
Good point - yes Safari was updated to 14. Thinking about it, my MBP16 has not had the Safari update, so maybe that what this is actually about. I'll do the 0.115 update and try again.

**Comment by zacwest** [comment] 2020-09-21 06:54
Sounds good. Please report back if it is still not working.

Closing as a (Mac-side) duplicate of #925.

**Closed by zacwest** 2020-09-21 06:54 UTC
Labels: bug, mac

**Comment by ntompson** [comment] 2020-09-28 23:15
Hi - just confirming that the issue has been resolved following an update to HA 0.115. All good now. Thanks for your help.
