### ISSUE TITLE
App not refresh after reopen

### ISSUE THREAD

**Issue by tmjpugh** [home-assistant/iOS#1973] opened 2021-12-05 14:21 UTC
**iOS device model, version and app version**

Model Name: iPhone XR
Software Version: 15.1
App version: 2021.266

**Home Assistant Core Version**

 Docker Core 2021.11.3

**Describe the bug**
When open app, app does not refresh. All data displayed is stale and input/button press do not work.

if force close app by app selector>>swipe up to close, the app refreshes upon next start and all working OK

**To Reproduce**
Open App
Switch to other 
Wait 5hr or more(time appears related)
Open app
Data is old and actions have no effect

**Expected behavior**
App refresh all data after open from paused/sleep state

**Screenshots**

**Additional context**

I believe a notification can be received during this time but actions in notifications do not work. I not check this to clarify

**Comment by deluxestyle** [comment] 2021-12-06 08:54
Sounds like the same issue
https://github.com/home-assistant/iOS/issues/1801

**Comment by TomBrien** [comment] 2021-12-06 08:56
Yep this is a duplicate of #1801, closing in favour of the original. Please let me know if I've got this wrong

**Closed by TomBrien** 2021-12-06 08:56 UTC
Labels: bug, ios
