### ISSUE TITLE
iOS 14b5 refreshes page when tapping button/toggle/etc

### ISSUE THREAD

**Issue by zacwest** [home-assistant/iOS#925] opened 2020-08-18 20:37 UTC
This appears to be a system bug introduced in b5. This reproduces in Safari the browser. There may be some mitigation we can do in the frontend if we can figure out what's going wrong, but it's very much on Apple to fix.

**Comment by zacwest** [comment] 2020-08-18 20:39
File as Feedback FB8453144:

> Crash when tapping button in web view and Safari (new in 12.0b5)
> Visit https://demo.home-assistant.io and tap any button/toggle. Safari and a WKWebView will both have the rendering process crash.

**Comment by vistalba** [comment] 2020-08-19 20:02
Same issue here. Is there any known workaround?

**Comment by zacwest** [comment] 2020-08-19 20:04
There is no known workaround at this time.

**Comment by vistalba** [comment] 2020-08-19 20:15
Any kind of logs or infos I can provide to help fix or workaround the issue?

**Comment by SeanPM5** [comment] 2020-08-19 20:25
Best thing we can do right now is to send feedback to Apple using the Feedback Assistant app. Link them to the demo website (https://demo.home-assistant.io/) so it is easier for their engineers to reproduce without installing and configuring an app. The more bug reports they get, the better.

And then fingers crossed that a fix comes in iOS 14 beta 6 🤞

**Comment by mcooksey** [comment] 2020-08-19 20:34
I just filed a feedback as well. Fingers crossed for a fix in beta 6, this is going to be a painful wait.

**Comment by vistalba** [comment] 2020-08-19 20:36
I filled one as well. 
Really hard as it doesn‘t work in App, Safari, Chome and any other Browser. Hopefully there will be a fix or at least a workaround soon.

**Comment by chrisduk112** [comment] 2020-08-19 21:54
I’ve got this issue too! 
Annoying.

**Comment by TheJulianJES** [comment] 2020-08-20 00:30
Also happening on the latest macOS Developer Beta 5 in Safari.

**Comment by chipriley** [comment] 2020-08-20 01:11
Feedback/bug submitted to Apple, also. Very frustrating.

**Comment by MwC-Trexx** [comment] 2020-08-20 18:38
Feedback submitted to Apple (iOS)

**Comment by bramkragten** [comment] 2020-08-20 20:11
This seems to be an issue with the mwc elements we use.

**Comment by chrisduk112** [comment] 2020-08-25 17:33
New iOS 14 beta 6 out :) I’m downloading and I’ll confirm it it fixed it shortly

**Comment by mcooksey** [comment] 2020-08-25 17:46
Just finished installing - everything appears to be working!

Thank goodness we only had to wait a week for the next beta... that was painful.

**Comment by chrisduk112** [comment] 2020-08-25 17:51
It works again! 💯

**Comment by Teglgaard** [comment] 2020-08-25 19:30
With beta 6 the issue has been resolved. I suggest to close the issue.

**Comment by TomBrien** [comment] 2020-08-25 19:43
Yep just confirmed on my phone (iOS really does spend ages "preparing update" sign). Closing this as resolved.

**Closed** 2020-08-25 19:44 UTC
Labels: bug, iOS 14
