### ISSUE TITLE
Sensor complications Apple Watch disappear and appear again

### ISSUE THREAD

**Issue by octaviz** [home-assistant/iOS#982] opened 2020-09-04 09:39 UTC
**iOS device model, version and app version**

Model Name: iPhone 11 Pro
Software Version: iOS 14 beta 5/6/7
App version: 2020.5.2

**Home Assistant Core Version**
0.104.0

**Describe the bug**
I have a rectangular "Graphic" complication with several sensors configured and it has always worked without interruptions, since the beta 5 of iOS 14 the complication appears and disappears when it wants, both inside mired Wifi and outside with 4G (I attach screenshots)
**To Reproduce**
You don't have to do anything, just wait for it to happen, because I don't know of any mechanism to force the bug
**Expected behavior**
It should show the complication with the sensor data all the time
**Screenshots**

![1](https://user-images.githubusercontent.com/856579/92225239-3a18b880-eea3-11ea-824a-5fde22baa6f9.jpg)
![2](https://user-images.githubusercontent.com/856579/92225240-3ab14f00-eea3-11ea-9a1e-1f11fe62f99a.jpg)

**Additional context**
When the complication appears working you can be for a long time, 15-30 minutes approx. Most of the day is not working, as in capture 2
This happens even if you have the iOS Home Assistant App open or closed, it is indifferent.

**Comment by djungelola** [comment] 2020-09-07 05:47
Have exactly the same problem. Havent figured it out when/why it sometimes works.

/Ola

**Comment by octaviz** [comment] 2020-09-07 06:57
I think it is a problem with iOS 14 beta and the Home Assistant App in its latest version from the App Store, before I updated it, it worked fine. Let's see if they solve it soon.

**Comment by luukd** [comment] 2020-09-12 15:35
I have the same problem with the Home Assistant app from the App Store on iOS 13.7 and WatchOS 6.2.8:

![IMG_3132](https://user-images.githubusercontent.com/1858881/92999061-3d084e80-f51e-11ea-8e69-f2f6187e3cc9.png)

**Comment by octaviz** [comment] 2020-09-18 19:16
With the last version 2020.6.1 don't working, continue same problem

**Comment by velaar** [comment] 2020-09-25 13:54
Same issue on latest Watch OS/iOS. 
Also complications randomly stop. 

I wonder if a separate WatchOS app is warranted.

**Comment by octaviz** [comment] 2020-09-28 09:14
After doing a thousand tests, in the configuration of the App I have removed the Internal IP, I have only configured the External IP, so it seems that if you are outside your internal network the sensors are working "almost" all the time. The problem is in the internal / external connections so it seems. Try it to see if it works like me

**Comment by luukd** [comment] 2020-10-02 14:42
I'm not using the internal/external option. The app always uses the same URL that works both inside and outside my network. I've configured the internal URL to see if it makes a difference, but the result remains the same: the template is never rendered.

**Comment by octaviz** [comment] 2020-10-02 15:11
It seemed to me that it worked with only External IP, but no, until yesterday it worked for me but not today, I don't know what is really happening but it must be something complex to solve, I even configured a new hassio in another site with the same result, no  updates, random, intermittent connections with the  Watch, anyway ...

**Comment by djungelola** [comment] 2020-10-02 15:27
I have tested with both 2020.6.2 and 2020.7.3 which both works fine. Had the same issues as described above before.
My complcations are updated fine. Only using external IP.

**Comment by velaar** [comment] 2020-10-02 15:30
> I have tested with both 2020.6.2 and 2020.7.3 which both works fine. Had the same issues as described above before.
> My complcations are updated fine. Only using external IP.

So the issue is intermittent.

Is there a clear doc on how Apple Watch requests the complication update? Does it do it via phone? On its own? Which protocols and ports are involved?

**Comment by octaviz** [comment] 2020-10-02 15:31
It worked for me 2-3 days, but not anymore, not even with external IP, Internal, both, I'll do more tests today if I can

**Comment by zacwest** [comment] 2020-10-11 07:08
I believe this will be resolved by #1168 and #1176 and will be in the [TestFlight beta](https://www.home-assistant.io/ios/beta) starting in 2020.7 (6) or later. Please give it a try and report back if this is incorrect.

The app on iOS and the watch on watchOS both do complication updates. There's a division of responsibility after the above referenced changes:

- The iOS app and the watchOS app can talk to each other and share information. This is how the complication configuration is passed around. When this occurs from iOS, it may have added the rendered template values. When the watchOS app receives an update, it will schedule a complication update.
- When a watchOS background task (we schedule for :00, :15, :30, :45) occurs it will attempt to render templates and then schedule a complication update. This only happens when you have a Home Assistant complication on the active watch face. From my testing of a `{{ now() }}`-valued complication recently, this tends to occur within ~2-3 minutes of the scheduled time.
- If the watchOS background task fails for connectivity reasons (e.g. no Wi-Fi signal or the server is down; contrast this to e.g. your reverse proxy returning a 503 error) the system will continue to retry it and will wake the watchOS app up with the values and then we schedule a complication update.
- When a complication update is requested, the watchOS app will grab the latest locally-fetched data and use that to decide what values the complication is delivered. If, for some reason, the app has no rendered templates it will show the raw text for the template which is what was being shared/happening above. I believe this will happen a lot less now.

There are further things we can do in the future to try and trigger more complication updates but the exact limits are only published for a few of them so it will require a lot of experimentation to figure out if it would be worthwhile. 

There's some flakiness around the watchOS-driven requests: it doesn't let us know the Wi-Fi information of the watch. The method we use to decide if you are internal or external is based on the passed-from-iOS-to-watchOS configuration values.

**Closed by zacwest** 2020-10-11 07:08 UTC
Labels: bug, ios
