### ISSUE TITLE
“mdi:icon”

### ISSUE THREAD

**Issue by Stefano0042** [home-assistant/iOS#564] opened 2020-03-10 09:21 UTC
mdi:  customized icon in cards are disappearing at every screen refresh/app boot, they will reappear temporarily e.g. if you click on Map in main left menu.

**Comment by TomBrien** [comment] 2020-03-10 11:30
Are you seeing the same in safari on iOS?

**Comment by Stefano0042** [comment] 2020-03-10 14:21
Hello Tom,
in Safari is the same behavior, all is ok only with standard icon.

Stefano Serafini
mobile: +39 334 6174934
Via Girolamo Frescobaldi, 6
10154 Torino (TO)
email: stefano.net@hotmail.it

On 10 Mar 2020, at 12:30, Tom Brien <notifications@github.com> wrote:

﻿

Are you seeing the same in safari on iOS?

**Comment by Stefano0042** [comment] 2020-03-10 14:23
Hello Tom, in safari is the same behavior, standard icons are contrarily fitting well..

Stefano Serafini
mobile: +39 334 6174934
Via Girolamo Frescobaldi, 6
10154 Torino (TO)
email: stefano.net@hotmail.it

On 10 Mar 2020, at 12:30, Tom Brien <notifications@github.com> wrote:

﻿

Are you seeing the same in safari on iOS?

**Comment by masonevans** [comment] 2020-06-09 15:53
@TomBrien I am experiencing the same issue.  If I kill the app (or the OS has killed the app in the background), when it launches it shows all the custom icons with no problem.  However if the app has been in the background and I bring it to the foreground, custom icons disappear.  If I do a "pull-down-to-refresh" then the icons show up again.

From what I can tell this started happening with HA 110.0, which makes sense given the new icon handling.  It's definitely happening in 110.3, I have not tried and further versions.

It's hard to tell if this can be reproduced in Safari as Safari has different background behavior.  It's actually quite similar to the old issue where the app would go blank when you brought it out of the background until you did a refresh.

**Comment by TomBrien** [comment] 2020-06-10 10:56
Hi sorry I think I missed the reply to this some how. Sorry given that this was introduced in a Home Assistant Core update and someone has reproduced in Safari this is a front end issue

**Comment by robbiet480** [comment] 2020-06-11 04:25
@balloob @bramkragten Any ideas? Seems similar to https://github.com/home-assistant/frontend/issues/5868

**Comment by bramkragten** [comment] 2020-06-11 07:16
That isn't related, but I'll see if I can reproduce.

**Comment by TomBrien** [comment] 2020-06-17 20:14
Jacob Hopkins over on the forums put up a post yesterday which is similar to this. Looks like no MDI icon when connected locally. True for both app and Safari https://community.home-assistant.io/t/ios-local-network-partial-functionality/205334

**Comment by balloob** [comment] 2020-06-17 20:21
Icons are using IndexedDB now and no longer just one big file that we dump in the DOM. Is IndexedDB available?

**Comment by olijouve** [comment] 2020-06-17 23:28
> Is IndexedDB available?

What do you mean, do we have something particular to enable to make IndexDB available ?

Same issue for me, IOS companion is unusable since 0.110, same under ios Safari.

**Comment by robbiet480** [comment] 2020-06-20 00:08
@balloob Yep, and if it wasn’t, wouldn’t no icons load?

**Comment by balloob** [comment] 2020-06-20 00:11
I think it still should, just no local caching.

**Comment by bramkragten** [comment] 2020-07-27 15:36
I could not reproduce this, is this still a problem?

**Comment by jacobhopkins117** [comment] 2020-07-27 15:40
I no longer see this behavior on the iOS app. It seemed to be resolved in a
0.112.x release. Apologies for not updating the thread on my experience.

**Closed** 2020-07-27 17:38 UTC
