### ISSUE TITLE
Don't auto-enable scene actions

### ISSUE THREAD

**Issue by Nixon506E** [home-assistant/iOS#2356] opened 2023-05-02 17:25 UTC
### Discussed in https://github.com/home-assistant/iOS/discussions/1771 with no response from lead devs

<div type='discussions-op-text'>

<sup>Originally posted by **jason0x43** January 27, 2021</sup>
**Is your feature request related to a problem? Please describe.**

I don't typically want to show all my scenes in the actions list on my Apple Watch, so I disable some of them in the companion app. That works well enough, except for dynamic scenes. Those are discarded and re-created every time HA restarts, so they keep ending up back in my actions list (I'm assuming because the app sees them as new scenes).

**Describe the solution you'd like**

I propose that scene actions not be automatically enabled (or that a switch is added to change the default behavior). They should be easy to enable, as they are now, but the user should be able to decide whether to add them.

**Additional context**
</div>

**Comment by cpvbruno** [comment] 2023-05-05 00:54
+1

**Comment by normand198** [comment] 2023-10-11 19:16
Yep, please fix or give us an option...

**Comment by bgoncal** [comment] 2023-11-01 13:02
https://github.com/home-assistant/iOS/pull/2437

**Comment by LagaV** [comment] 2023-11-04 19:13
+1

**Comment by randall-au** [comment] 2024-02-28 14:19
+1

**Comment by pashdown** [comment] 2024-02-28 16:55
> +1

This was fixed in [#2437](https://github.com/home-assistant/iOS/pull/2437). Give it a try.

**Comment by bcmitri** [comment] 2024-02-28 17:57
This was not fixed. A workaround was provided, but the root cause still persists.

**Comment by randall-au** [comment] 2024-02-28 17:58
> > +1
> 
> This was fixed in [#2437](https://github.com/home-assistant/iOS/pull/2437). Give it a try.

I don’t think #2437 addresses this issue. The issue here is that when scenes are generated on the fly they get enabled in the mobile app and show up on the watch. I assume this is because scenes in general get enabled by default. When a scene is generated on the fly, it apparently gets destroyed and recreated resulting in a “new” scene that get enabled on the watch by default.

**Comment by randall-au** [comment] 2024-02-28 17:59
> This was not fixed. A workaround was provided, but the root cause still persists.

What was the workaround?  I missed that.

**Comment by pashdown** [comment] 2024-02-28 18:12
> What was the workaround? I missed that.

Home Assistant App -> Settings -> Companion App -> Actions -> (SCENE ACTIONS) Select All (OFF)

**Comment by randall-au** [comment] 2024-02-28 18:27
> > What was the workaround? I missed that.
> 
> Home Assistant App -> Settings -> Companion App -> Actions -> (SCENE ACTIONS) Select All (OFF)

Unfortunately that doesn't address the issue.  I have an automation that takes a snapshot of the state of several lights using scene: create so that it can put the lights back as they were after the automation runs.  Every time this automation runs, the created scene gets re-enabled in the app causing it to show up on my watch.  This happens even if Select All is OFF.  I'm thinking if select all is off, scenes should default to off as well.

**Comment by bcmitri** [comment] 2024-02-28 18:36
I think that’s exactly what we are all saying. The issue has _not_ been fixed.

**Comment by randall-au** [comment] 2024-02-29 01:01
> I think that’s exactly what we are all saying. The issue has _not_ been fixed.

One quasi work around would be to use scene.delete after the scene is activated.  In my case, one of my applications is when there is motion detected at my front door, I take a snapshot of all the lights on the front of the house and then turn everything on full brightness.  After a few minutes I activate the snapshot scene to put everything back like it was.  By deleting the scene after I activate it, I can limit the time it is shown on the watch to just a few minutes.  Not perfect, but better than having it on there all the time.

**Comment by sciorty** [comment] 2024-04-15 09:26
> > > What was the workaround? I missed that.
> > 
> > 
> > Home Assistant App -> Settings -> Companion App -> Actions -> (SCENE ACTIONS) Select All (OFF)
> 
> Unfortunately that doesn't address the issue. I have an automation that takes a snapshot of the state of several lights using scene: create so that it can put the lights back as they were after the automation runs. Every time this automation runs, the created scene gets re-enabled in the app causing it to show up on my watch. This happens even if Select All is OFF. I'm thinking if select all is off, scenes should default to off as well.

Same problem here. Any update?

**Closed** 2024-05-06 07:49 UTC
Labels: in progress, watch

**Comment by sciorty** [comment] 2024-05-06 07:56
Finally! Any clue on when the next release will be?

**Comment by bgoncal** [comment] 2024-05-06 07:57
> Finally! Any clue on when the next release will be?

To the AppStore, probably in the end of this month, in Testflight, this week.
