### ISSUE TITLE
New core update breaking ipad frontend

### ISSUE THREAD

**Issue by LucHyg** [home-assistant/iOS#2983] opened 2024-09-06 20:57 UTC
**iOS device model, version and app version**

Model Name: ipad 5th generation 
Software Version: 16.7.10
App version: 

**Home Assistant Core Version**
2024.9.1

**Describe the bug**
Fronted does not load, reported by several users on Facebook group.
Just loops and settled on a black screen
**To Reproduce**
Cannot use at all, reset device, reinstall app does not fix 
**Expected behavior**
Normal HA interface 
**Screenshots**

**Additional context**

Rolling back Core version fixed it

**Comment by zhekch** [comment] 2024-09-06 21:51
Same issue on the iphone app

**Comment by bgoncal** [comment] 2024-09-06 22:10
Both iOS 16? How does it behave on iOS Safari? Can you send a screen recording?

**Comment by LucHyg** [comment] 2024-09-06 22:24
I only use the ios app on my ipad tablets. Don't use apple anywhere else.
If I navigate to my HA on Safari on my ipad it works. Just the app not working.

I suspect it has something to do with changes to the sections feature.
I saw another post of someone with the exact same issue on Facebook running a fire tablet. And it seemed it was only the dashboard using the sections featured (not comfirmed) just from observations.
 But the issue is cropping up for a more IOS devices as well.
________________________________

**Comment by bgoncal** [comment] 2024-09-06 22:33
Please send the Facebook links here as well and a screen recording from Safari usage and app usage.
You can also try to reset front end cache through companion app settings >> debugging

**Comment by LucHyg** [comment] 2024-09-06 22:42
Here is the link for one from facebook 

https://www.facebook.com/share/p/GzAAJoivNkQB7yVx/


This guy has a fire tablet, but his dashboard is doing the exact thing everyone elses is doing.
https://www.facebook.com/share/v/gYfm5BweJ2YL6j9r/

Sorry I only have Ipads for HA dashboards and wouldnt know the first thing about IOS, screen recordings or anything.
apologies.

**Comment by LucHyg** [comment] 2024-09-06 22:43
Also I have tried the reset front end cache and that has not worked unfortunately.
Also reinstalled entire APP

**Comment by LucHyg** [comment] 2024-09-06 22:43
> Both iOS 16? How does it behave on iOS Safari? Can you send a screen recording?

Yes 16.7.10

**Comment by bgoncal** [comment] 2024-09-06 22:48
> Here is the link for one from facebook 
> 
> 
> 
> https://www.facebook.com/share/p/GzAAJoivNkQB7yVx/
> 
> 
> 
> 
> 
> This guy has a fire tablet, but his dashboard is doing the exact thing everyone elses is doing.
> 
> https://www.facebook.com/share/v/gYfm5BweJ2YL6j9r/
> 
> 
> 
> Sorry I only have Ipads for HA dashboards and wouldnt know the first thing about IOS, screen recordings or anything.
> 
> apologies.

https://support.apple.com/en-gb/102653

**Comment by LucHyg** [comment] 2024-09-06 22:51
Thanks, not at home until monday evening here in Australia so will have to wait until im back then. Maybe @zhekch can do this as they are experiencing the same issue on their iphone.

**Comment by coulicoulaser** [comment] 2024-09-07 07:58
Hello, 
I also have the problem, here's a recording of my screen. Obviously this affects a lot of people on iOS. I'm using iOS 16.5. I keep reloading the page but it's extremely slow ...
Thanks for your help

https://github.com/user-attachments/assets/264cda1c-c19e-4833-b3c7-3fd3bb2e3338

**Comment by LucHyg** [comment] 2024-09-07 08:21
Yeah that's exactly what's happening. Spot on. Are you using the new sections dashboard theme?

**Comment by bgoncal** [comment] 2024-09-07 08:22
> Hello, 
> I also have the problem, here's a recording of my screen. Obviously this affects a lot of people on iOS. I'm using iOS 16.5. I keep reloading the page but it's extremely slow ...
> Thanks for your help
> 
> https://github.com/user-attachments/assets/264cda1c-c19e-4833-b3c7-3fd3bb2e3338

For you the same happens in iOS Safari?

**Comment by coulicoulaser** [comment] 2024-09-07 08:27
> > Hello, 
> > I also have the problem, here's a recording of my screen. Obviously this affects a lot of people on iOS. I'm using iOS 16.5. I keep reloading the page but it's extremely slow ...
> > Thanks for your help
> > 
> > https://github.com/user-attachments/assets/264cda1c-c19e-4833-b3c7-3fd3bb2e3338
> 
> For you the same happens in iOS Safari? 

Unfortunately, yes
![image](https://github.com/user-attachments/assets/9e97707c-58bc-4cc4-8a2a-82b8d94ed02f)

**Comment by coulicoulaser** [comment] 2024-09-07 08:28
> Yeah that's exactly what's happening. Spot on. Are you using the new sections dashboard theme?

Yes ! I'm using it

**Comment by Leventionz** [comment] 2024-09-07 13:20
I managed to capture a log of some sort, not sure if this helps but I have the same error, also using Sections.
My other none sections dashboards work okay. Very occassionally, I can get the dashboard to load but very low success rate 1/100. My other devices are fine, it's only affecting my 5th gen iPad.

Logger: frontend.js.modern.202409060
Source: components/system_log/init.py:333
First occurred: 13:57:44 (2 occurrences)
Last logged: 14:00:22
Uncaught error from WebKit 605.1.15 on iOS 16.7.10 Script error. null @:0:0

**Comment by nnae06** [comment] 2024-09-07 14:37
I have the same problem with my Ipad 4 Mini.

Logger: frontend.js.modern.202409060
Källa: components/system_log/__init__.py:333
Inträffade först: 16:29:09 (1 händelser)
Senast loggade: 16:29:09
Uncaught error from WebKit 605.1.15 on iOS 15.8.3 Script error. null @:0:0

**Comment by benfpalmer** [comment] 2024-09-07 18:55
Updating to iOS 17.6.1 resolved this for me

**Comment by zhekch** [comment] 2024-09-07 20:57
ios 16.6 safari

https://github.com/user-attachments/assets/9f3609ba-8af9-4401-a9db-38467773dc96

**Comment by bramkragten** [comment] 2024-09-09 07:53
Thanks for reporting this issue, I will need a little more information as I'm not able to reproduce the issue.

Is this happening on every dashboard or only specific ones? 
Do you also get this issue in safe mode?
Could you try to find out what causes the issue by eliminating parts of the dashboard?

**Comment by piitaya** [comment] 2024-09-09 08:00
I'm able to reproduce it using browser stack with iPad and iOS 16.

**Comment by AlexKusnezov** [comment] 2024-09-09 15:39
same here iPhone10,4 iOS 16.7.10 blank screen, even in broswers (Safari+Chrome). Cleared cache, delete app, even a fiull phone reset. Nohting helped

**Comment by piitaya** [comment] 2024-09-09 15:44
You found a fix for that issue. It will be part of the next patch release.

**Comment by elyobelyob** [comment] 2024-09-14 13:37
Surely this rendering my iOS app impossible to use would qualify for its own patch release? Waiting 5+ days for a fixed issue is too long?

**Comment by LucHyg** [comment] 2024-09-14 14:28
Not sure about what is too long. But we have 9.1 out now and still no fix.
This issue kills my dashboards across all my ipads HA apps and ios browsers.


________________________________

**Comment by LucHyg** [comment] 2024-09-14 14:29
> We found a fix for that issue. It will be part of the next patch release.

Thanks for your hard work. Looking forwards to updating. Will the fix be mentioned in the next patch notes?  I'll keep a look out for it

**Comment by elyobelyob** [comment] 2024-09-17 20:23
Very happy that the fix is now out.

**Closed** 2024-09-17 22:01 UTC
Labels: bug, ios
