### ISSUE TITLE
Bluetooth Connections Report

### ISSUE THREAD

**Issue by snakedm** [home-assistant/iOS#1617] opened 2021-05-02 13:34 UTC
Is it possible to create the bluetooth report from iPhone to HA? As it also exists on Android.
In order to be able to report to HA which devices are connected to the iPhone.

![Screenshot 2021-05-02 at 14 32 52](https://user-images.githubusercontent.com/75492000/116815005-76480a00-ab53-11eb-9e1c-de098aa3ef50.png)

Thanks a lot!

**Comment by TomBrien** [comment] 2021-05-02 13:42
Duplicate of #956. If wrong please reopen

**Closed** 2021-05-02 13:42 UTC
Labels: feature-request, ios
