### ISSUE TITLE
Auto update app

### ISSUE THREAD

**Issue by niccolobusato** [home-assistant/iOS#1268] opened 2020-11-09 11:18 UTC
**Is your feature request related to a problem? Please describe.**
Every time that a new release is available we need to download that, unzip and then move to the application folder

**Describe the solution you'd like**
Auto install the new update on app restart

when opening the app ask for a restart and update automatically!

**Additional context**

**Comment by TomBrien** [comment] 2020-11-09 11:24
This is essentially a duplicate of #1243

The app is currently a beta release so the update procedure is not the final one. Once out of beta the app will be available through the AppStore which will handle the updates and additional potential frameworks are being considered (see linked issue above). Also, if Apple do announce the rumoured TestFlight for macOS tomorrow, it is possible that will be used during beta.

**Closed by TomBrien** 2020-11-09 11:24 UTC
Labels: feature-request, mac
