### ISSUE TITLE
Apple Watch Series 3 Ring Image/Text

### ISSUE THREAD

**Issue by colethegamer123** [home-assistant/iOS#1188] opened 2020-10-13 05:32 UTC
**Model Name: Apple Watch Series 3
Software Version: WatchOS 6.2.8
App version: Pre-Release /2020.7/6
Home Assistant Core Version: 0.116.2**

**Describe the bug**
Creating Ring Image or Ring Text does not work properly, the complication is added and refreshed but only the inside picture or the text can be seen. I can manually set the value to 1.0 what should be a full ring, but nothing happens.

You can see the "T" sign on the bottom right.
![image](https://user-images.githubusercontent.com/62310407/95819276-e6ad4c00-0d25-11eb-8590-8443da4f22c5.png)

**To Reproduce**
Set any Ring Image / Ring Text setting.

Here are the settings for the given Test picture.
![image](https://user-images.githubusercontent.com/62310407/95819325-06447480-0d26-11eb-8102-2e7eea828502.png)

**Expected behavior**
It should draw the ring around the text / image.

Thank you very much for your hard work.
Best regards,

**Comment by mountainsandcode** [comment] 2020-10-13 09:44
This is a duplicate of #1127 (which was fixed in #1168) and #1170. There is already a beta version out where you can test this before the next update is released.

**Comment by colethegamer123** [comment] 2020-10-13 12:26
Please read first the Issue, as you see im on the beta version since its released.

**Comment by mountainsandcode** [comment] 2020-10-13 12:29
> Please read first the Issue, as you see im on the beta version since its released.

My bad, I was too quick - I saw the /6 at the end and assumed that was the version, rather than build number 🙈

**Comment by colethegamer123** [comment] 2020-10-13 12:30
No problem mate, Lets see maybe someone knows a workaround or it will be fixed sometime :)

**Comment by colethegamer123** [comment] 2020-10-16 13:45
Reinstalled Watch Full Reset
Reinstalled App Phone/Watch
Recreated Complications now on watchOS 7.0.2 but still the same problem.

**Comment by zacwest** [comment] 2020-10-16 23:21
One way to get an idea what's happening here is to grab the Console logs from the Watch. The app should be logging what it's doing for the most part, especially it if hits an unexpected scenario. If you've got a Mac, you can:

1. Plug the iPhone into your Mac
2. Open `/Applications/Utilities/Console.app`
3. Select the Apple Watch in the "Devices" list in the sidebar
4. Search for `WatchExtension-Watch` at the top. Right now, this is the name of the process. This may change later (if you're reading these instructions in the future).
5. Trigger a complication update (using the app 2020.7 or later) by editing the complication. You may need to tap on the complication to launch the app and make a sync happen. This should trigger a complication refresh.

**Comment by colethegamer123** [comment] 2020-10-17 08:54
I does not have MAC and I know nobody who has :(

**Comment by zacwest** [comment] 2020-10-18 05:30
Please let me know if 2020.7 (7) released earlier today resolves the issue as it does have some changes in how this complication will load.

**Closed** 2020-10-18 16:01 UTC
Labels: bug, ios, watch
