### ISSUE TITLE
Actions buttons on Watch and iOS should be swipeable to prevent accidental touches.

### ISSUE THREAD

**Issue by brayStorm** [home-assistant/iOS#1569] opened 2021-04-03 21:13 UTC
**Is your feature request related to a problem? Please describe.**

Actions on Apple Watch and iPhone are very prone to accidental presses. 

**Describe the solution you'd like**

Can they be changed, or have the option in App Configuration, to make them swipe-to-confirm? Similar to old swipe to unlock iPhone?

**Additional context**

**Comment by bcmitri** [comment] 2021-04-05 01:00
Seems like a similar request to #1345.

**Comment by zacwest** [comment] 2021-07-18 04:44
I agree, feels like a duplicate of this one, thanks!

**Closed by zacwest** 2021-07-18 04:44 UTC
Labels: feature-request, ios
