### ISSUE TITLE
Actions available based on context

### ISSUE THREAD

**Issue by ehendrix23** [home-assistant/iOS#1689] opened 2021-06-24 18:12 UTC
**Is your feature request related to a problem? Please describe.**

Certain actions are to turn something on or off, lock or unlock something. Currently one has to define 2 actions (lock and unlock for example) and both are available all the time.

**Describe the solution you'd like**
Ability to have actions available based on conditions. For example, when something is locked, the action to unlock is available but not the action to lock. And when then unlocking the action to unlock becomes unavailable but the one to lock becomes available.
This would then follow "conditions"  syntax within home assistant (https://www.home-assistant.io/docs/scripts/conditions/)

**Additional context**

**Comment by TomBrien** [comment] 2021-06-24 18:16
I feel this is kind of a duplicate of #1669. Template-able text and icons would allow for the UI changes you'd like and the actual logic is already available through automations. What do you think?

**Comment by ehendrix23** [comment] 2021-06-24 18:25
I would say similar but not duplicate as that one is about making complications template-able whereas you could indeed for my request do it with making the actions (icon, text, color) template-able as well.

**Comment by TomBrien** [comment] 2021-06-24 18:31
Fair point sorry I messed up the original. Yeah template-able action properties is what's needed here and the option to hide based on the value of a template. Problem I see I going to be pushing data frequently enough to watches you be useful. Actions on other devices should be ok with this.

**Closed** 2021-07-18 04:46 UTC
Labels: feature-request, ios
