### ISSUE TITLE
Sidebar menu labels sometimes aren’t localized

### ISSUE THREAD

**Issue by e28eta** [home-assistant/iOS#1295] opened 2020-12-06 01:18 UTC
**iOS device model, version and app version**

Model Name: iPad Pro (12.9-inch) (3rd generation)
Software Version: 14.2
App version: 2020.7 (11)

**Home Assistant Core Version**

0.118.4

**Describe the bug**
Sometimes when I open the app on my iPad, the sidebar labels are wrong. Looks like these are the un-localized labels? Everything is set to en-US, and it’s weird to see blank/snake case labels.

**To Reproduce**
I don’t know

**Expected behavior**
correct UI labels

**Screenshots**

![image](https://user-images.githubusercontent.com/483223/101268918-a8c51680-371d-11eb-96c1-61e34acb9b61.jpeg)

**Additional context**

Sometimes pull-to-refresh fixes it, sometimes it doesn't. I don't know.

**Comment by TomBrien** [comment] 2020-12-14 09:02
Do you still see this? Looks like a reoccurrence of home-assistant/frontend#7596 which was supposed to be fixed by home-assistant/frontend#7597

**Comment by e28eta** [comment] 2020-12-19 23:42
Hi @TomBrien,

I still don't know how to reproduce, but I haven't seen it this week. I'm on 0.118.5 now.

I'm happy for this issue to be closed, and if I do continue to see it I'll check the frontend project issues.

Thanks!

**Comment by TomBrien** [comment] 2020-12-20 07:49
Reproducing is tricky as it's a race condition. Will close here. I suggest you chase this on the frontend repo.

**Closed by TomBrien** 2020-12-20 07:49 UTC
