### ISSUE TITLE
Home Assistant won't install on Watch 3.Gen

### ISSUE THREAD

**Issue by M-Krieger** [home-assistant/iOS#2568] opened 2024-02-01 12:29 UTC
Watch:
Model Name: Apple Watch 3. Gen
Software Version: 8.8.1
App version: Can't install app on Watch (see bug description)

iPhone: 
Model Name: iPhone 13 mini
Software Verson: 17.3
App Version: 2024.1 (2024.535)

**Home Assistant Core Version**
2024.1.5

**Describe the bug**
I can't get my watch (see specs above) to install the Home Assistant App for it. Every other App is installable. When I try to install by Watch-App on iPhone it just starts spinning pretending installing the app. Some seconds later after spinning I see button "install" again.

When I try to install on the Watch AppStore itself it's resulting in an error: "Your request could not be completed. Please try again later".

I'v resetted the Watch and tried installing many times in the last week hoping for a temporary error but it seems it's not temporary.

**To Reproduce**
- already had home assistant installed on iPhone
- used my wife's old watch, disconnected it from her account and resetted it. Then connect it to my iPhone
- all available apps for my watch has been installed except home assistant.

**Expected behavior**
- Let me install Home Assistant on my watch.
- I checked the requirements and my watch should work

Anyone else with a 3. generation watch faces the same problem?
Any logs I can provide to assist in debugging the problem?

**Comment by mminges** [comment] 2024-02-01 23:59
Ran into exact same issue today. Also have a 3rd gen watch and was working on iOS actions for the watch but the actions weren’t showing up so I tried reinstalling the HA companion app. Same behavior as explained in the issue. It acts like it’s installing then goes back to Install within 15 seconds usually.

**Comment by colethegamer123** [comment] 2024-02-07 19:09
I have totally the same issue as you described. Also Apple Watch Series 3. It would be really good to make it work with this older models again, everything was working perfectly earlier and this older watch is more than enough for HA actions.

**Comment by bgoncal** [comment] 2024-02-08 14:07
I had some time today and I ran it on Apple Watch Seris 3 watchOS 8 simulator (since I dont have a real series 3 to test) and it is working fine.

Before moving on with the investigation maybe it worth removing HA completely from watch and iPhone, reboot, wait a few minutes and try again.
Afaik if you see it available to install it means it is compatible with your device, so if it is not installing it may be an issue on iOS/watchOS side, but let me know and I can help follow up with Apple if thats the case

**Comment by colethegamer123** [comment] 2024-02-08 14:24
I tested with multiple IOS device at home to connect the Apple Watch 3 there. I also tried to totally reset the Apple Watch. The whole problem is started with it was installed there since years but Actions and Sensors cannot be updated what ever you do, so no new updates came from phone side what could reach the Watch, this is why I went to reinstall HA to Watch, but cannot. Everybody is in the same shoe as I see.

**Comment by bgoncal** [comment] 2024-02-08 14:30
One thing you could try is to use the testflight application and go back a few versions to see if it changes something

**Comment by M-Krieger** [comment] 2024-02-09 08:53
Hey there, thank you for your feedback.

I've tried installing with some other Builds from the past with TestFlight but same issue for me. I also tried using the simulator but can't reproduce the setup, cause xcode only offers 8.5.1 for Watch 3 instead of 8.8.1?

**Comment by M-Krieger** [comment] 2024-02-09 20:29
I tried again using the simulator but can't get it working. I chose an iPhone 13 Mini iOS 17.2 (my device) and paired this simulator with a watch 3 with watchOS 8.5 (only available). Well - I don't know how to install home assistant on a simulated watch.

I searched the web for watch 8.8.1 issues and found an issue which shows the same behavior and also on watchOS 8.8.1. Maybe the bug isn't present in 8.5?
https://github.com/Automattic/pocket-casts-ios/issues/1217
https://github.com/Automattic/pocket-casts-ios/pull/1253

Have a nice weekend

**Comment by M-Krieger** [comment] 2024-02-10 21:45
> I have the same issue. It worked since few days ago

I'm not sure, it's working for you now or it's not working since three days ago?

**Comment by matatools** [comment] 2024-02-10 21:48
Now is not working. Few days ago (maybe before some update) it was regularly working

**Comment by M-Krieger** [comment] 2024-02-12 11:01
Do you happen to know what has been updated and maybe caused the issue? I tried previous versions with testflight but still can't get it to install.

**Comment by matatools** [comment] 2024-02-12 15:59
Unfortunately I cannot understand what may have caused the issue

**Comment by nzrutman** [comment] 2024-02-12 21:02
Same problem. Trying from App Store on watch itself: "Unable to complete request, try again later". Trying from Watch app on phone (Home Assistant under Available Apps, Install): spinny circle for about 4 seconds, then stops and returns to "Install" button.
WatchOS 8.8.1
Model A1861

**Comment by M-Krieger** [comment] 2024-02-20 10:34
Is there anything we can provide helping to debug the issue?

**Comment by bgoncal** [comment] 2024-02-20 10:44
I'll try to get an AW series 3 to reproduce this, but installation issues usually are on Apple's side, and since it worked fine on the simulator, I can't quickly spot what could have gone wrong.
You can see on App Store that the minimum required version is watchOS 5 https://apps.apple.com/nl/app/home-assistant/id1099568401

Has anyone opened a support ticket with Apple to investigate this issue?

**Comment by Moe555** [comment] 2024-02-20 20:51
Same issue here (also with some other WatchOS apps, but "only" 4 out of 40+).

Didn't open a ticket so far, since I have the feeling Apple won't actually help with a 6+ year old device.
Besides that I just saw the option to call them and was too lazy to do so :)

**Comment by rick2d2** [comment] 2024-02-27 02:26
New to HA and was eager to try the Apple Watch integration. Like everyone else here the app won't load on my Series 3 with WatchOS 8.8.1. Tried hard resetting the phone, watch, deleting/reinstalling HA on phone, even erase all contents on the watch with no success. Tried on my wife's SE Gen 2 and it worked perfectly. 

Got a bad feeling that this is a ploy to get me to buy a new watch.

**Comment by bgoncal** [comment] 2024-02-27 09:52
Im experimenting in this [PR](https://github.com/home-assistant/iOS/pull/2609) based on some other app that had the same problem

**Comment by nzrutman** [comment] 2024-02-27 16:05
> Im experimenting in this [PR](https://github.com/home-assistant/iOS/pull/2609) based on some other app that had the same problem

That looks like a promising patch! Thanks for looking into this.

**Comment by bgoncal** [comment] 2024-02-27 17:51
I made a special build in testflight to see if the fix worked, please try version 2024.3 (567) and let me know if it works

**Comment by Moe555** [comment] 2024-02-27 19:15
> I made a special build in testflight to see if the fix worked, please try version 2024.3 (567) and let me know if it works

Thanks

For me it's still showing 2024.2 (2024.561) as newest build in Testflight.
I used this link to join:
https://testflight.apple.com/join/1AlPbnLZ

Does it just take some more time to show the new build / you are still waiting for review/approval?
(Or do I need to use another link/code??)

**Comment by bgoncal** [comment] 2024-02-27 20:09
Apologies, apple is still reviewing, should be available tomorrow or thursday

**Comment by M-Krieger** [comment] 2024-02-28 00:22
Can confirm, installs on my Apple Watch! Thank you very much! Only reason I tried an Apple Watch :)

**Comment by bgoncal** [comment] 2024-02-29 13:34
Heads up that the PR was not merged yet, so newer testflight builds will have the issue.

**Closed** 2024-03-04 21:20 UTC
Labels: bug, ios

**Comment by scottcopus** [comment] 2024-03-12 02:37
This is still a problem for me on my Watch 3 (8.8.1) and iPhone 12 (17.4).  "unable to complete request" shown on the Watch's App Store when trying to install.  Is the official public release suppose to work or do I need to sign up for Apple testflight and get a different version?  Thanks!

**Comment by bgoncal** [comment] 2024-03-12 07:33
> This is still a problem for me on my Watch 3 (8.8.1) and iPhone 12 (17.4).  "unable to complete request" shown on the Watch's App Store when trying to install.  Is the official public release suppose to work or do I need to sign up for Apple testflight and get a different version?  Thanks!

For now TestFlight version has the fix

**Comment by netthera** [comment] 2024-09-09 10:12
I had a similar problem with the Ultra 2, thought it was working for a while it stopped working. I deleted the app from the watch and then I could not reinstall from the iPhone, as it was described above, it would try to install and then would stop without installing.  
I was able to successfully install it using the App-store on my watch and then everything was working again.
