### ISSUE TITLE
Long Reload time when network is changed

### ISSUE THREAD

**Issue by ebnerjoh** [home-assistant/iOS#521] opened 2019-12-21 07:39 UTC
Hi, 

I have the experience that the v2.0 is very picky on network changes, which I didnt experience in the old version.

E.g.: When waking up from sleep or when moving from LTE to WLAN or the other way around the v1 was adopting much faster. The v2 needs sometimes very long and in addition I have to restart the app.
It also shows me much more oftne the request to enter username and password, after killing the app and starting again it takes the prefilled values.

Br,
Johannes

**Comment by sj3fk3** [comment] 2019-12-21 08:40
Experienced from the start when beta testing 2.0 (I always swipe the app and restart it).

**Comment by 0x3333** [comment] 2020-06-04 12:21
Same here. I always get to the username and password screen, need to force close and open again.

**Comment by TomBrien** [comment] 2020-06-04 12:23
This is a duplicate of #426 so I’ll close in favour of that

**Closed** 2020-06-04 12:23 UTC
Labels: duplicate
