### ISSUE TITLE
Feature Request: Store Actions in Home Assistant

### ISSUE THREAD

**Issue by jeffehobbs** [home-assistant/iOS#928] opened 2020-08-20 13:51 UTC
PROBLEM: Every reinstall of the Home Assistant app requires a fresh new setup of Actions. This is somewhat tiresome.

PROPOSED SOLUTION: Actions should be able to be defined and stored in Home Assistant (either in .yaml or otherwise) so they can be synced back to the app after clean install.

**Comment by TomBrien** [comment] 2020-08-20 14:33
Totally agree and this is something I'm working on. In fact there is a PR on the core side, we're just working out the best implementation. This is a duplicate of #494. So I'll close in favour of that.

**Closed** 2020-08-20 14:33 UTC
Labels: duplicate, feature-request
