### ISSUE TITLE
iOS 14.6b2 icons missing

### ISSUE THREAD

**Issue by apmosss** [home-assistant/iOS#1625] opened 2021-05-06 08:24 UTC
**iOS device model, version and app version**

Model Name:  iPhone 12
Software Version:  14.6 Beta2
App version:  2021.4.1

**Home Assistant Core Version**

2021.5.0

**Describe the bug**
All icons missing on latest 14.6 Beta2. Manually refreshing brings everything back. Tried phone restart, reset frontend cache. Happens everytime I open the app.

**To Reproduce**

**Expected behavior**

**Screenshots**

![icons2](https://user-images.githubusercontent.com/56562838/117267953-7865dd80-ae5f-11eb-8a0b-8d962587728f.jpg)
![icons1](https://user-images.githubusercontent.com/56562838/117267959-79970a80-ae5f-11eb-823b-2465d3f03c21.jpg)

**Additional context**

**Comment by robbiet480** [comment] 2021-05-06 08:25
Why didn't you fill out the issue template? Fill out the template and provide some details then let me know and I will reopen this issue.

**Comment by robbiet480** [comment] 2021-05-06 08:32
Can you please provide some screenshots of what "All icons missing" looks like? On what screen is this issue happening? If its happening in your frontend and not any app UI, does the issue also happen in Safari or just in the HA app?

**Comment by apmosss** [comment] 2021-05-06 08:38
Updated first post with screenshots. First one is when I open the app. Second one is when I manually refresh.

**Comment by hallenmaia** [comment] 2021-05-08 23:19
Same here on iOS 
![Uploading F0BC9AAC-7135-413C-9F65-6FE2FDD9A926.png…]()
14.6 (18F5055b)

**Comment by danuals** [comment] 2021-05-11 06:17
And another here iOS 14.6
App 2021.5

**Comment by niso01** [comment] 2021-05-25 22:52
I have the same problem.
Both on iPhone 12 and iPad Pro 10.5.
IOS 14.6 (no beta)
App versin 2021.5
Core 2021.5.5

**Comment by niso01** [comment] 2021-05-26 19:04
Same discussion at Home Assistant Forums:
https://community.home-assistant.io/t/ios-app-bug-icons-don-t-show/307058

**Comment by jonare77** [comment] 2021-05-26 21:31
Just installed 14.6, same bug here. Everytime the app is started you need to manually refresh the screen by draging down. Strange bug.

**Comment by rtclauss** [comment] 2021-05-26 23:03
Also on macOS 11.4 with the macOS Companion app
App Version:  2021.05 (2021.150)
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1046259/119742034-88fce880-be4c-11eb-8785-59475d397d92.png">

**Comment by LeChuck2909** [comment] 2021-05-27 11:27
> Just installed 14.6, same bug here. Everytime the app is started you need to manually refresh the screen by draging down. Strange bug.

Same here.

And thx for the draging down work around, didnt know that.

**Comment by niso01** [comment] 2021-05-28 10:31
Good news
https://github.com/home-assistant/frontend/pull/9280

**Comment by TomBrien** [comment] 2021-05-28 10:54
As this is confirmed as frontend tracked in home-assistant/frontend#9269 and fixed in home-assistant/frontend#9280 I'll close here.

**Closed by TomBrien** 2021-05-28 10:54 UTC
Labels: bug, ios
