### ISSUE TITLE
Add more controls for information to be sent, and default off or wizard

### ISSUE THREAD

**Issue by gdt** [home-assistant/iOS#536] opened 2020-01-24 18:09 UTC
This is about 2019.1.    I  realize there are many use cases and desires, and I may be a bit unusual.  I have a HA instance with one or two sensors each from many locations, and people that want to watch their sensor and get notifications.  So I don't want reports about the SIM or bssid of these people's phones, and I don't want entities created for them.  I don't even want reports or entities about their battery levels.

It seems that one can enable/disable a number of things within the app, such as location, but it also seems that a number of things are reported anyway, or at least default to on.   So I would ask that there be checkboxes in the config for all things (groups) that can be reported, and that at onboarding, there be a screen to check the things to report.  I think this would be useful for many people, as there are now a very large number of sensors and if not wanted they become noise.  (It is great to have them for those that want them; I can see a normal HA instance with two people and two phones wanting to see this.)

(I think that the config menu item works now, and that the only interaction with permissions is that without permission things won't work, but even with say location permission you can still configure off location.)

**Comment by zacwest** [comment] 2020-06-25 01:32
Closing as a duplicate of #358. II think this is the route to go for choosing which sensors are actively sent.

**Closed by zacwest** 2020-06-25 01:32 UTC
Labels: feature-request
