### ISSUE TITLE
App frozen with no UI after iOS 13.5.1 update

### ISSUE THREAD

**Issue by scstraus** [home-assistant/iOS#669] opened 2020-06-17 11:41 UTC
**iOS device model, version and app version**

Model Name: iPhone X
Software Version: iOS 13.5.1
App version: 2020.1

**Home Assistant Core Version**

.111.3

**Describe the bug**

iOS app doesn't display the UI directly after iOS update 13.5.1. Cannot access sidebar menu, cannot access any UI elements. Was working fine on same hass version prior to 13.5.1 update. UI displays correctly in all other browsers on windows, iOS, fireos, and macos including fully kiosk, chrome, firefox, and iOS safari. Nothing I can find helps, quitting, rebooting, etc.

**To Reproduce**

Open the app.

**Expected behavior**

A UI

**Screenshots**

![image](https://user-images.githubusercontent.com/7644023/84893865-3cd3f080-b0a0-11ea-9290-224abee2e994.png)

**Additional context**
[My full config is published here if you need any context](https://github.com/scstraus/home-assistant-config)

**Comment by zacwest** [comment] 2020-06-17 19:43
Are you able to open the menu and get to the App Configuration? Being able to take a look at the logs would be very helpful in this situation.

**Comment by scstraus** [comment] 2020-06-17 20:08
No, I couldn't open the app configuration either.. But I figured out what happened. It wasn't the update after all, but some lovelace code that I've had working fine for the last 20 or so releases that just now decided to blow up only the iOS app. This is the offending code. It doesn't like the vertical-stack-in card nested inside a vertical stack. If I have them nested like this the iOS app blows up (and only the iOS app, all other browsers work):


```
  - type: vertical-stack
    cards:

    - type: 'custom:weather-card-chart'
      title: Weather / Air Quality
      weather: weather.openweathermap
      sun: sun.sun
      mode: hourly

    - type: custom:vertical-stack-in-card
      cards:
      - type: "custom:button-card"
        name: Hlubočepy
        styles:
          name:
            - color: var(--ha-card-header-color)
          card:
            - padding: 8px 0px

      - type: custom:air-visual-card 
        air_pollution_level: sensor.hlubocepy_air_pollution
        air_quality_index: sensor.hlubocepy_air_quality
        main_pollutant: sensor.u_s_main_pollutant_2
        hide_title: true
        svg_location: "/local/icons/aqi_icons"

    - type: custom:vertical-stack-in-card
      cards:

      - type: "custom:button-card"
        name: Home
        styles:
          name:
            - color: var(--ha-card-header-color)
          card:
            - padding: 8px 0px

      - type: custom:air-visual-card 
        air_pollution_level: sensor.home_air_pollution
        air_quality_index: sensor.home_air_quality
        main_pollutant: sensor.u_s_main_pollutant_2
        hide_title: true
        svg_location: "/local/icons/aqi_icons"
```

But if I take out the enclosing vertical stack like so, the iOS app works fine:

```
#  - type: vertical-stack
#    cards:

  - type: 'custom:weather-card-chart'
    title: Weather / Air Quality
    weather: weather.openweathermap
    sun: sun.sun
    mode: hourly

  - type: custom:vertical-stack-in-card
    cards:
    - type: "custom:button-card"
      name: Hlubočepy
      styles:
        name:
          - color: var(--ha-card-header-color)
        card:
          - padding: 8px 0px

    - type: custom:air-visual-card 
      air_pollution_level: sensor.hlubocepy_air_pollution
      air_quality_index: sensor.hlubocepy_air_quality
      main_pollutant: sensor.u_s_main_pollutant_2
      hide_title: true
      svg_location: "/local/icons/aqi_icons"

  - type: custom:vertical-stack-in-card
    cards:

    - type: "custom:button-card"
      name: Home
      styles:
        name:
          - color: var(--ha-card-header-color)
        card:
          - padding: 8px 0px

    - type: custom:air-visual-card 
      air_pollution_level: sensor.home_air_pollution
      air_quality_index: sensor.home_air_quality
      main_pollutant: sensor.u_s_main_pollutant_2
      hide_title: true
      svg_location: "/local/icons/aqi_icons"

```

**Comment by scstraus** [comment] 2020-06-17 20:08
Let me know if you want to investigate further, otherwise I will close it.

**Comment by olijouve** [comment] 2020-06-18 00:11
I have the same issue. 

I do use  'custom:vertical-stack-in-card' but at top level, not embeded in a vertical-stack

**Comment by robbiet480** [comment] 2020-06-18 00:57
Can we loop in the card author here?

**Comment by olijouve** [comment] 2020-06-18 08:38
I fixed it with this PR, from vertical-stack-in-card project.
https://github.com/ofekashery/vertical-stack-in-card/pull/93/files

Indeed it wasn't the right place for it, but you don't know until you know ;)

**Comment by scstraus** [comment] 2020-06-18 16:16
> I fixed it with this PR, from vertical-stack-in-card project.
> https://github.com/ofekashery/vertical-stack-in-card/pull/93/files
> 
> Indeed it wasn't the right place for it, but you don't know until you know ;)

I had tried this patch once previously to fix card placement and didn't get any change so reverted.. I just tried it again based on your suggestion, and this time restarted homeassistant and it now fixed my card placement, but only kind of fixed this issue. Now the cards using vertical-stack-in card simply don't display on iOS (you can see them start to render but then they disappear). Dut they do display on other browsers. But it at least doesn't crash the entire app anymore.  So that's a step up from before.

**Comment by olijouve** [comment] 2020-06-18 17:22
That’s strange. My UI is full of pseudo cards that use that plugin. 
Did you delete the .js.gz file in the same directory ?
Maybe a reset of frontend cache on your app could help. Disable wifi on your phone and restart compnion app. It will allow to access config screen. At the very bottom Of settings you have a button to reset frontend cache.

**Comment by scstraus** [comment] 2020-06-19 00:56
I didn't delete the .js.gz file, should I have done that?

I did reset the frontend cache already but it didn't change anything.

**Comment by olijouve** [comment] 2020-06-19 11:18
I think the .js.gz can be load in place of the .js because deflated/compressed content can be prefered by browsers to save bandwidth. 
In your case .js.gz il the compressed version of the old .js so your change could not have been taken in effect.
I would delete it or recreate it with gzip cmd line(if gzip exists in the system/docker)

**Comment by scstraus** [comment] 2020-06-19 16:44
Good to know, that might very well be my issue. I will gzip the new version and put it there and restart everything, clear caches and try again.

**Comment by scstraus** [comment] 2020-06-20 00:24
So, no dice.. I deleted the .gz version and gzipped the new one up and put it next to the new .js version and restarted hass and cleared all my caches and tried again and same result... They aren't all in 1 column like when I had the new stack-in card on .107, but only about the first 6 cards stack right and then the rest go into one long column.

**Comment by robbiet480** [comment] 2020-06-20 07:54
Closing as this appears to be an issue not caused by us and also is conveniently fixed. Feel free to keep chatting, just trying to keep issue #’s low.

**Closed by robbiet480** 2020-06-20 07:54 UTC
Labels: 2020.1, bug
