### ISSUE TITLE
Homebrew Cask support for MacOS

### ISSUE THREAD

**Issue by aditsachde** [home-assistant/iOS#1037] opened 2020-09-18 19:30 UTC
**Is your feature request related to a problem? Please describe.**

Homebrew is a really great tool to install software on MacOS and has support for GUI applications via `brew cask`. Being able to install Home Assistant Companion via Homebrew would be quite useful.

**Comment by mweinelt** [comment] 2020-09-19 14:45
The cask name currently creates a conflict on repology as it reuses the same name as the home-assistant core project.

https://repology.org/project/home-assistant/versions

This leads to messed up version bump notifications for package maintainers.

I raised the issue over at homebrew, where this was packaged and they refered me back here, since the apps bundle name is what creates the conflict in the first place.

https://github.com/Homebrew/homebrew-cask/pull/89544#issuecomment-695215076

**Comment by zacwest** [comment] 2020-09-20 03:31
Forgive my ignorance -- is it expected behavior that homebrew cask entries are mixing with other package repositories? Just glancing through the casks, I see things like Docker and Coda -- where it's the same product/company or name collision -- also mixing together.

The bundle name they are referencing there is the user-facing name of the application when it's running. I'm not sure it would be a better user experience to have an even longer application name. Is there any method to get Repology there to splinter the packages?

**Comment by zacwest** [comment] 2020-09-20 03:32
I didn't notice this earlier cask ticket, but it was implemented in the above-referenced PR on cask, so I'm closing this one as completed.

If you'd like to start a conversation on changing the bundle name or some in-this-repo change to support cask differently, feel free to open a ticket separately for it.

**Closed by zacwest** 2020-09-20 03:32 UTC
Labels: feature-request, mac
