### ISSUE TITLE
Faster location updates while driving + charging

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/iOS#787] opened 2020-07-15 07:34 UTC
**Is your feature request related to a problem? Please describe.**
Not really a problem, but an idea to improve location updates (which has been getting a lot of love lately)

**Describe the solution you'd like**
With the popularity of CarPlay, many iPhone users plug their phones into the car USB port while driving. And when your phone is plugged in to a power source like this, battery life is not a concern obviously. So the idea here is maybe when under these circumstances, the app can perform more aggressive location updates.

It would basically check if Activity sensor is "Automotive" **and** Battery State sensor is "Charging." If both of these things are true, enter faster location update mode. 

Benefit of this approach is that if location was updated in a faster/consistent/reliable basis, that would not only improve the app, but the many integrations that rely on a phones device tracker to be useful - the [Proximity](https://www.home-assistant.io/integrations/proximity/) integration, [Waze Travel Time](https://www.home-assistant.io/integrations/waze_travel_time/) integration, and many more.

**Comment by TomBrien** [comment] 2020-07-17 08:58
This is a partial dupe of #644 which I'm not sure should be closed to be honest

**Comment by bcmitri** [comment] 2020-07-19 17:49
+1 on this. As #644 suggested, I’d like to see more frequent sensor updates whenever the device is plugged in. This goes double if I’m driving. 

I’d like to see logic that increases the frequency of updates when the device is plugged in and/or moving. Conversely, it should decrease the frequency of updates when the device is unplugged and/or stationary and/or in low power mode. 

I was actually on the verge of creating automations to do exactly this, so I’m interested to see if anything will be implemented here that will take care of some (or all) of it for me.

**Comment by zacwest** [comment] 2020-07-19 18:01
Although we can choose to generate more location events when the phone is actively moving, we cannot make the app launch more often in the background to generate more events otherwise. You'll be better served by using Shortcuts to force the app to update.

**Comment by bcmitri** [comment] 2020-07-19 18:05
Good to know....  In that case, I’ll just add my support to Sean’s original request and take care of the rest through location request notifications.

**Closed** 2021-07-18 04:21 UTC
Labels: feature-request
