### ISSUE TITLE
When trying activate script from shortcuts or using new control center buttons

### ISSUE THREAD

**Issue by firejackson1** [home-assistant/iOS#3012] opened 2024-09-17 00:59 UTC
Logger: homeassistant.util.logging
Source: util/logging.py:95
First occurred: 7:00:18 PM (223 occurrences)
Last logged: 8:52:34 PM

Exception in updated when handling msg on 'hass.agent/devices/DESKTOP': '{"serial_number":"118f2395-adc1-43c2-9347-05ec884a4099","device":{"identifiers":"hass.agent-DESKTOP","manufacturer":"HASS.Agent Team","model":"Microsoft Windows NT 10.0.22631.0","name":"DESKTOP","sw_version":"2.0.1"},"apis":{"notifications":true,"media_player":true}}' Traceback (most recent call last): File "/config/custom_components/hass_agent/__init__.py", line 144, in updated update_device_info(hass, entry, payload) File "/config/custom_components/hass_agent/__init__.py", line 29, in update_device_info device_registry.async_get_or_create( File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 834, in async_get_or_create device = self.async_update_device( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1066, in async_update_device self.hass.verify_event_loop_thread("device_registry.async_update_device") File "/usr/src/homeassistant/homeassistant/core.py", line 462, in verify_event_loop_thread frame.report_non_thread_safe_operation(what) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation report( File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report _report_integration(what, integration_frame, level, error_if_integration) File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration raise RuntimeError( RuntimeError: Detected that custom integration 'hass_agent' calls device_registry.async_update_device from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#device_registryasync_update_device at custom_components/hass_agent/__init__.py, line 29: device_registry.async_get_or_create(. Please report it to the author of the 'hass_agent' custom integration.

**Comment by bgoncal** [comment] 2024-09-17 01:08
The title of the issue is unrelated to the logs.

About the script from shortcuts and control center, I just merged a fix for it, as soon as possible it will be available in App Store as 2024.9.1

**Comment by firejackson1** [comment] 2024-09-17 01:43
O ok thank you either way

**Comment by bgoncal** [comment] 2024-09-17 22:05
Please update the app and confirm the issue has been fixed

**Comment by mattBatc** [comment] 2024-09-18 12:15
I'm in iOS 18, HA app version 2024.9.1, and scripts are not firing from my home screen widget

**Comment by bgoncal** [comment] 2024-09-18 12:36
Closing the issue since it looks like the release ix was successful, feel free to reopen

**Comment by mattBatc** [comment] 2024-09-18 12:39
I said it DID NOT fire the script as intended?

**Comment by bgoncal** [comment] 2024-09-18 12:43
> I said it DID NOT fire the script as intended?

Apologies, misread your message, can you try deleting the widget and adding them back? If it doesn't work, please export your logs and submit to me:
https://forms.gle/rZthn7H7pmZLyWjR8

**Comment by firejackson1** [comment] 2024-09-18 13:40
They released a update yesterday that fixed it

**Closed** 2024-09-18 13:42 UTC
Labels: bug, ios
