### ISSUE TITLE
Stuck in login loop on iOS14 beta 5

### ISSUE THREAD

**Issue by bobvmierlo** [home-assistant/iOS#937] opened 2020-08-24 19:49 UTC
**iOS device model, version and app version**

Model Name: iPhone 11
Software Version: 14.0
App version: Latest, can't check since i'm stuck in a login loop

**Home Assistant Core Version**

0.114.3
**Describe the bug**
I removed the mobile app integration from HA and reset the app, because I wanted a fresh install of the integration. Did this quite a few times before. But now I'm stuck on a login loop, which throws an error after 2 login tries.
Unfortunately there is no way for me to get into my HA from the app now.
**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/38190383/91089267-a0a40800-e653-11ea-8284-41f0c975350a.png)

**Additional context**

The embedded browser in which you login throws the following error on the third try:
```
There has been a repeating problem:
https://MYHASURL.nl/auth/authorize?response-type=code&client_id=https://home-assistant.io/iOS&redirect_uri=homeassistant://auth-callback
```

**Comment by TomBrien** [comment] 2020-08-24 20:02
This is caused by #925. There is a more detailed summary on the alert [here](https://alerts.home-assistant.io/#apple-betas-2020.markdown). 

A fix has been merged into WebKit and we hope that will be included in beta 6. Going to close this as a duplicate. Let me know if this is not a duplicate.

**Closed** 2020-08-24 20:03 UTC
Labels: duplicate
