### ISSUE TITLE
IOS app Status bar doesn’t match theme even i disabled CCH and use hex color

### ISSUE THREAD

**Issue by horacecar** [home-assistant/iOS#558] opened 2020-03-02 19:46 UTC
IOS app Status bar doesn’t match theme even i disabled CCH and use hex color
![20200303034534 (2)](https://user-images.githubusercontent.com/44496483/75711717-d221c380-5d01-11ea-88bc-0a466bf28ce1.jpg)
![20200303034534 (1)](https://user-images.githubusercontent.com/44496483/75711723-d3eb8700-5d01-11ea-9f78-e9bb49100fe6.jpg)

----------------------------------------------------------------------------

Google Light Theme:
  # Header:
  
  accent-color: var(--primary-background-color)
  app-header-color: var(--primary-background-color)
  app-header-background-color: var(--primary-background-color)
  app-header-text-color: var(--primary-background-color)
  # Main Interface Colors
  primary-color: var(--primary-background-color)
  light-primary-color: var(--primary-color)
  primary-background-color: "#F8F8F8"
  secondary-background-color: var(--primary-background-color)
  divider-color: var(--primary-background-color)
  # Text
  primary-text-color: "#424242"
  secondary-text-color: "#5F6267"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#717171"
  # Sidebar Menu
  sidebar-icon-color: var(--app-header-text-color)
  sidebar-text-color: '#424242'
  sidebar-background-color: "#FFFFFF"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#5F9BEA"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color))
  # States and Badges
  state-icon-color: "#5F6267"
  state-icon-active-color: "#5F9BEA"
  state-icon-unavailable-color: var(--disabled-text-color)
  # Sliders
  paper-slider-knob-color: "#5F9BEA"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  # Labels
  label-badge-background-color: "#F8FAF9"
  label-badge-text-color: "#4D5575"
  label-badge-red: "#C7484C"
  label-badge-green: "#6DC071"
  label-badge-blue: "#51AAD1"
  label-badge-yellow: "#D9B757"
  label-badge-gray: "#5F6267"
  # Cards
  ha-card-border-radius: "15px"
  ha-card-box-shadow: 1px 1px 5px 0px rgb(230, 230, 230)
  paper-card-background-color: "#FFFFFF"
  paper-listbox-background-color: "#FFFFFF"
  # Switches
  switch-checked-button-color: "#5F9BEA"
  switch-checked-track-color: "#75a2f0"
  switch-unchecked-button-color: "#5F6267"
  switch-unchecked-track-color: "#888b91"
  # Toggles
  paper-toggle-button-checked-button-color: var(--switch-checked-button-color)
  paper-toggle-button-checked-bar-color: var(--switch-checked-track-color)
  paper-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
  paper-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)
  # Table
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
  data-table-background-color: var(--primary-background-color)

**Comment by TomBrien** [comment] 2020-03-02 21:35
Possible duplicate of #557.

What version of Home Assistant Core are you running. Are you setting the theme using the `frontend.set_theme` service?

**Comment by horacecar** [comment] 2020-03-03 05:28
![20EB26AC-BD53-412C-8822-477DD23D591B](https://user-images.githubusercontent.com/44496483/75745617-d62a0180-5d52-11ea-869a-72809258b47e.jpeg)
@TomBrien Hello Tom,  i am using 0.106.2, actually i am choosing the theme directly in the drop down menu under the user profile, i dont want to use frontend.set_theme, because the will change all different user’s theme, all of my family wanna use different theme as their hobby, once i use this command will force unified change all of their theme with the same theme .

**Comment by TomBrien** [comment] 2020-03-03 07:06
Unfortunately changing theme through that drop down does not allow the app to detect the change. See the docs [here](https://companion.home-assistant.io/docs/troubleshooting/faqs#the-status-bar-top-bar-with-cellwi-fi-strength-does-not-match-my-theme)

**Comment by horacecar** [comment] 2020-03-03 07:58
@TomBrien Thanks , all right , then is there any script can generate an event for the companion app to detect the theme change to avoid changing all user's theme to a same theme?

**Comment by MattiBaat** [comment] 2020-05-21 19:49
According to the companion app documents it uses the primary-color for the status bar (https://companion.home-assistant.io/docs/integrations/theming/). 
The companion app should use the app-header-background-color.

**Closed** 2020-06-11 04:30 UTC
