### ISSUE TITLE
left menu doesn't slide

### ISSUE THREAD

**Issue by michalk-k** [home-assistant/iOS#1534] opened 2021-03-13 13:40 UTC
Model Name: iPhone X
Software Version: iOS 14.1
App version: 2021.3 (2021.77)
But it exists since I remember (more than year)

Home Assistant Core Version
HA Core 2021.1.5

**Describe the bug**
When application is run for the first time, and left menu is pulled out, vertical swiping on this menu doesn't work. In result it makes impossible to access some menu items which initially don't fit the screen size. The only option to activate menu using hamburger icon. This way is 100% reliable so far. 
After activating vertical swiping, it remains available even for the menu activated by pulling out. 

**To Reproduce**
1. make sure the application is killed
2. start application
3. pull left-menu by swiping from left edge to the right
4. try to scroll menu content vertically by swiping vertically - it doesn't work
5. close menu by clicking in other ha area or swiping the menu to the left.
6. use top-left hamburger menu to open menu
7.  try to scroll menu content vertically by swiping vertically - this time it works.

**Expected behavior**
See "To Reproduce" section

**Screenshots**
the video shows the behavior. Unfortunately doesn't show "moving "finger" during the first attempt
https://youtu.be/ed8fgVyNd4s

**Additional context**

**Comment by Rajaikumar-iOSDev** [comment] 2021-03-14 03:22
@zacwest Can you assign this to me?

**Comment by TomBrien** [comment] 2021-03-25 09:14
This looks like a duplicate of #559. Can someone confirm?

**Comment by bgoncal** [comment] 2024-04-12 13:15
I believe this is fixed by now right? I tried to reproduce and wasn't able to achieve it.
Feel free to reopen if needed

**Closed by bgoncal** 2024-04-12 13:15 UTC
Labels: bug, ios
