### ISSUE TITLE
Identify whether macbook is connected to charger or not

### ISSUE THREAD

**Issue by dbdmdbdmdbdm** [home-assistant/iOS#1130] opened 2020-10-01 16:00 UTC
**Is your feature request related to a problem? Please describe.**

Would like an attribute of the mac to state whether my macbook is plugged in or not. Charging vs not charging does not help because it will say "not charging" when it is at 100%

**Describe the solution you'd like**
An additional sensor or attribute of a sensor to state whether it is connected to a power source

**Additional context**

**Comment by zacwest** [comment] 2020-10-02 16:42
This sounds more like a bug than a feature request. The intended behavior is that the state is `Full` when connected to a charger at 100% and `Not Charging` when not connected at 100%.

**Comment by SeanPM5** [comment] 2020-10-02 17:20
Hmm, I do think this FR might have a valid use case though.

With the "Optimized Battery Charging" setting in macOS Big Sur you could be connected to a power source but still be in a "Not Charging" state. Since that mode charges in shorter bursts over a longer period of time rather than straight through in one blast. 

So it could be bouncing between Charging/Not Charging even if the laptop was plugged in the entire time. In theory anyway... I haven't paid very close attention to the battery sensors yet. But that might be something to keep an eye on?

**Comment by zacwest** [comment] 2020-10-02 17:24
We can detect when the optimize battery thing is happening, maybe we could extend the battery sensor on macOS to be:

- Not Charging (not plugged in)
- Full (plugged in, at 100%)
- Charging (plugged in, below 100%, not optimizing battery)
- Optimizing (plugged in, below 100%, optimize battery enable)

Not sure on the "Optimizing" name though.

**Comment by SeanPM5** [comment] 2020-10-02 18:31
I don't think "Optimizing" is clear enough personally. It sounds more like some maintenance/repair task rather than charging your battery.

I like "Optimized Charging" and it's closest to the actual wording used in macOS. 

But that _might_ get truncated in some Lovelace cards though so maybe "Charging (Optimized)" or "Charging - Optimized" would work best? Because if a few characters get cut off the end of that, you're still seeing the most important part.

**Comment by zacwest** [comment] 2020-10-02 18:52
That gives the impression that it will be increasing the level in the future. What do you think about "Not Charging (Optimized)"?

**Comment by SeanPM5** [comment] 2020-10-02 19:28
Yeah that sounds fine to me

**Comment by zacwest** [comment] 2020-10-02 19:56
Or maybe "Full (Optimized)"

**Closed** 2024-02-26 10:07 UTC
Labels: bug, mac
