### ISSUE TITLE
Companion app asks for credentials unnecessarily (iPhone)

### ISSUE THREAD

**Issue by VivantSenior** [home-assistant/iOS#426] opened 2019-08-10 10:48 UTC
Hi,

I'm logged in to my HA instance via iPhone app for few months. I noticed that the app asks me for login and pass but after pressing the refresh button (located in the right down of the login screen) app shows my lovelace screen (but without providing credentials).
I have 4 iPhones conneted to my HA.

In my opinion app shouldn't ask for the credentials if I'm not logged out.

Best,
Viv

**Comment by TomBrien** [comment] 2019-08-10 10:53
This is a known bug. Hopefully it will be addressed in the first update to 2.0 after release. In the meantime if you force quit the app and re open, you will be logged straight in.

**Comment by VivantSenior** [comment] 2019-08-10 10:56
Thanks for the prompt response. I noticed that after "page" refresh I'm logged in again. No need for app restart.

Any timeline for v2.0?

**Comment by TomBrien** [comment] 2019-08-10 12:05
2.0 is with Apple right now I believe. We’re at the mercy of their review timeline at the moment sadly.

**Comment by VivantSenior** [comment] 2019-08-13 12:30
Thank you, finger crossed

**Comment by VivantSenior** [comment] 2019-10-01 06:12
Any updates regarding version 2.0? The Apple had time to publish 4 versions of new iOS in less than 2 weeks.. hopely they have reviewed the app.

**Comment by TeNpoLe21** [comment] 2019-11-29 14:26
Any update on this issue? I never experienced it using the betas, but just yesterday started to see it with 2019.1. Login screen is displayed and a pull to refresh brings up my front end without entering credentials. Also, force closing the app and reopening gets rid of the login prompt.

**Comment by VivantSenior** [comment] 2019-12-01 07:53
The login screen still appears on the official release but now you need to close the app and open it again to enter HA.

**Comment by TomBrien** [comment] 2019-12-01 07:54
This is a known bug. You can just pull down to refresh to fix

**Comment by TomBrien** [comment] 2019-12-06 15:50
This is now understood and will be fixed in 2019.2. Issue is related to access token expiry

**Comment by TomBrien** [comment] 2019-12-06 15:52
This is now duplicated (essentially) by #475. I'm going to close this in favour of that which is already on the 2019.2 project.

**Comment by robbiet480** [comment] 2020-02-12 09:44
@VivantSenior @TeNpoLe21 @dummptyhummpty @TravelinMax @burkemw3 Is this still a problem? I'm unable to reproduce and will need more information.

**Comment by TeNpoLe21** [comment] 2020-02-12 12:50
@robbiet480 no longer an issue for me. Thanks!

**Comment by tybritten** [comment] 2020-02-12 12:51
Same. No longer an issue

**Comment by robbiet480** [comment] 2020-02-12 16:51
Woohoo!

**Comment by robbiet480** [comment] 2020-02-12 19:53
@apateluk reports they are still having this issue.

Can you describe exactly what is happening? What do you do to cause this to happen?

Thanks

**Comment by apateluk** [comment] 2020-02-12 19:57
Thanks for reopening the issue.
I’m observing the same behaviour as I have done for a while. 

Launch the home assistant app after a few hours, am usually presented with login screen.
Force closing the app in iOS and reopening goes straight to the dashboard as expected. Pull down (which I just learnt today) also works and avoids having to force close.

Thanks

**Comment by robbiet480** [comment] 2020-02-12 19:59
@apateluk So you open the app, and then put it into the background and then come back a few hours later and it's stuck in a bad state until refresh. You don't open it at all during that period?

**Comment by apateluk** [comment] 2020-02-12 20:17
Yes I believe so. I don’t open the app in between. I’ll check over the next day or so and be a bit more methodological.

**Comment by robbiet480** [comment] 2020-02-12 20:18
Okay, let me know.

**Comment by robbiet480** [comment] 2020-02-12 20:19
Oh and for the record, @TomBrien and I both tried to replicate this in the last 18 hours and were unsuccessful which is why it was closed. Not saying that it's an invalid issue/we don't believe, more so just pointing out its possible its transient or something changed.

Also, what version of Home Assistant Core are you on @apateluk?

**Comment by apateluk** [comment] 2020-02-12 20:25
Thanks, will keep you updated.

0.105.3 of HA Core 
2019.1 App version

**Comment by jsiemek** [comment] 2020-02-12 21:38
It never happened to me, but it sometimes happen to my wife and daughter. All 2019.1, 0.105.2.
So maybe it will never happened to you @robbiet480 and @TomBrien. What makes things much harder to investigate.

**Comment by TomBrien** [comment] 2020-02-12 21:45
I used to see this but have not had this in several months. Including when I tested earlier in a way which used to trigger it (airplane mode on for more than 30 minutes then airplane off and open app)

**Comment by VivantSenior** [comment] 2020-02-13 07:59
> @VivantSenior @TeNpoLe21 @dummptyhummpty @TravelinMax @burkemw3 Is this still a problem? I'm unable to reproduce and will need more information from at least some of you if it is still happening.

Yes. On average ones-twice a week.
0.105.3 of HA Core
2.0.0 (69) App version

**Comment by apateluk** [comment] 2020-02-13 21:22
Had it happen twice today, it seems to be between 4-6hours of app launch.

**Comment by VivantSenior** [comment] 2020-02-15 14:31
@robbiet480 I had the error today. Managed to extract logs:

```(text)
2020-02-15 09:26:23.524 [Debug] [com.apple.NSXPCConnection.user.endpoint] [NotificationService.swift:30] didReceive(_:withContentHandler:) > Added client event
2020-02-15 09:26:23.524 [Debug] [com.apple.NSXPCConnection.user.endpoint] [NotificationService.swift:35] didReceive(_:withContentHandler:) > Set bestAttemptContent
2020-02-15 09:26:23.524 [Error] [com.apple.NSXPCConnection.user.endpoint] [NotificationService.swift:38] failEarly(_:) > Failing early because Attachment dictionary not in payload!


--- Tried to open the App around 10:35 but received login screen. Pulled down the screen ---


2020-02-15 10:35:26.281 [Info] > Rotated file /private/var/mobile/Containers/Shared/AppGroup/[some GUID here]/logs/log.txt to /private/var/mobile/Containers/Shared/AppGroup/[some GUID here]/logs/log_2020-02-15_103526.txt
2020-02-15 10:35:26.282 [Verbose] [main] [OneShotLocationManager.swift:36] init(onLocation:) > LocationManager: Got location stored on manager <xxxx,yyyy> +/- X.xx m (speed xx.xx mps / course -xx.xx) @ 15/02/2020, 10:35:26
2020-02-15 10:35:26.283 [Info] > Home Assistant Version: 2.0.0 Build: 69 PID: 73778
2020-02-15 10:35:26.283 [Info] > XCGLogger Version: 7.0.0 - Level: Debug
2020-02-15 10:35:26.284 [Info] > XCGLogger writing log to: file:///private/var/mobile/Containers/Shared/AppGroup/[some GUID here]/logs/log.txt
2020-02-15 10:35:26.296 [Info] [main] [HAAPI.swift:477] SubmitLocation(updateType:location:zone:) > Location update payload: ["battery": 93, "gps": [xx.xxx, yy.yyy], "speed": xx.xxxxxx, "gps_accuracy": xx.xxxxxx, "vertical_accuracy": x.x, "altitude": xx.xxxxxx]
```

**Comment by VivantSenior** [comment] 2020-02-17 06:39
Yesterday, I had this error twice. Couldn’t find anything interesting in the logs (just my action to pull down the screen to refresh credentials - logs shows it as manual refresh of the location).

Could the battery saving mode cause this issue?

**Comment by apateluk** [comment] 2020-02-17 08:23
After observing over the weekend, I don't think it's "time" related. As the app behaved exactly as expected when going back in overnight.

**Comment by DigitalBites** [comment] 2020-04-05 03:53
I found this thread here as I've been searching on this same issue I'm exerepncing. I didn't experience it with the betas at all but I've seen it recently. Its pretty consistent but it takes time for it to re-trigger the issue.

**Comment by VivantSenior** [comment] 2020-04-06 06:16
I have stopped using "Low power mode" and the issue (I think) is gone. Please try to re-trigger the issue when low power mode is on.

**Comment by TomBrien** [comment] 2020-04-06 06:18
Do you mean when you have it enabled and less than 20 % battery or just have it enabled in general and have plenty of battery

**Comment by VivantSenior** [comment] 2020-04-06 06:19
@TomBrien yes, just to enable it in general.

**Comment by johansmitsnl** [comment] 2020-05-05 14:30
I still have this issue, need to force close the app and open it again. Running on 0.109.2 and latest app from the store. I experience this on a iPhone 11pro, and 6s with latest ios available. No battery power save mode enabled just normal connection.  I do experience it when.switching from WiFi to 4G. But this might be unrelated.

**Comment by johansmitsnl** [comment] 2020-05-17 18:15
I also want to mention when this occurs the information item tells there was a failed login attempt. Hope this information helps.

**Comment by zacwest** [comment] 2020-09-12 05:56
I believe this issue is resolved. Please open a new issue if you experience the problem again as the cause will likely be different.

**Closed by zacwest** 2020-09-12 05:56 UTC
Labels: 2020.1, bug
