### ISSUE TITLE
2024.7: watchOS - assist icon without assist being installed

### ISSUE THREAD

**Issue by m1ke-hub** [home-assistant/iOS#2876] opened 2024-07-28 09:08 UTC
**iOS device model, version and app version**
Model Name:  Apple Watch Ultra 2
Software Version: 10.5
App version: 2024.7 (2024.730)

**Home Assistant Core Version**
2024.7.3

**Describe the bug**
I never use assist and don't even have it installed, the icon in the Apple Watch app still shows up.

**To Reproduce**
Remove "conversation:" from configuration.yaml, open the app and the icon is still there.

**Expected behavior**
It should only be there if the user actually has it installed.

**Comment by bgoncal** [comment] 2024-07-29 10:52
For now the behavior of always showing Assist is intentional and does not rely on having or not Assist configured, like in HA UI, it is the standard. But thanks for the feedback, perhaps we can hide it in the future, if you want this to be implement faster please submit a feature request in Home Assistant community. For now, closing this issue since it's not a bug.

**Closed by bgoncal** 2024-07-29 10:52 UTC
Labels: enhancement, ios
