### ISSUE TITLE
iPadOS Card rendering issue since HA 2024.8.0

### ISSUE THREAD

**Issue by PRProd** [home-assistant/iOS#2908] opened 2024-08-08 20:26 UTC
**iOS device model, version and app version**
Model Name: iPad (7th generation)
Software Version: 17.6
App version: (2024.730)

**Home Assistant Core Version**
2024.8.0

**Describe the bug**
After upgrading Home Assistant core to 2024.8.0, the rendering of _some_ cards inside the iOS companion app has changed.  Rendering in Chrome, Firefox, Safari, and the Android app still behave as expected after the upgrade to HA 2024.8.0.

**To Reproduce**
 - Use HA Core 2024.8.0
 - Download [HA-Firemote](https://github.com/PRProd/HA-Firemote) available through HACS
 - Add one or more Firemote cards to your dashboard
<br>

**Expected behavior**
Rendering should look the same in the iPad companion app as it does everywhere else.
<br>

**Screenshots**

iPad Rendering through Safari

![image](https://github.com/user-attachments/assets/a34fbd1a-9d6e-4d86-82ca-9b76defdccb0)
<br>

iPad Rendering through Home Assistant iOS Companion App

![Image](https://github.com/user-attachments/assets/29907e3a-20b1-4372-b3c0-be2fa2d5e848)
<br>

**Additional context**
I have seen this behavior on a couple of other HACS cards as well, so I know it's not just limited to Firemote.  I am the author of the Firemote card, so if any card design changes need to be made, please let me know.

**Comment by bgoncal** [comment] 2024-08-09 16:01
`Companion App Settings >> Debugging >> Reset frontend cache` let me know if it helps, no change was done on the App side.

**Comment by PRProd** [comment] 2024-08-09 16:14
@bgoncal ~

Thank you for your reply.  I should have mentioned that I tried that multiple times before submitting the report.  I also restarted my iPad a few times too.

I just tried again.  I reset the frontend cache 4 times.  Stopped and restarted the iPad app.  Powered off, then powered on the iPad.  Pulled down on the dashboard to see the refresh throbber a frew times.  No change.

Since the iPad software hasn't changed on your end, I can only assume that something was changed in HA Core 2024.8.0 that somehow is affecting the way css, sizing, and spacing is being rendered by the iPad app.  That's just a guess on my part though.

**Comment by PRProd** [comment] 2024-08-09 16:39
This issue is not unique to me.  I just received this issue report from another Firemote user:
https://github.com/PRProd/HA-Firemote/issues/478

**Comment by PRProd** [comment] 2024-08-09 16:58
Another example of the rendering issue affecting a different card
https://github.com/vasqued2/ha-teamtracker-card/issues/95

**Comment by Kanecaine** [comment] 2024-08-09 17:11
Having some problems with custom "weather chart card" within the companion app only. It seems that variable values are not rendered correctly. More infos are described here:

https://github.com/mlamberts78/weather-chart-card/issues/222#issuecomment-2276674425

**Comment by vasqued2** [comment] 2024-08-09 23:11
I can confirm it is impacting cards rendered using variables in css styles.  Cards only using variables for content (i.e. icons or text) render fine.

https://github.com/vasqued2/ha-teamtracker/issues/171

**Comment by mjaksn** [comment] 2024-08-10 20:45
In my case, configuring a custom user-agent string in Kiosk Pro that matches Safari on a fully updated iPad fixed the layout issues. I also reproduced the layout issue in a previously unaffected browser by intentionally sending an outdated UA string. These observations make me wonder if the problems could be related to https://github.com/home-assistant/frontend/pull/16506.

**Comment by PRProd** [comment] 2024-08-10 23:52
As a status update, it appears that this issue still persists in 2024.8.1

**Comment by vasqued2** [comment] 2024-08-11 05:06
The order of the cards on a dashboard tab change how the cards behave.

I render different a version of my card based on the state of a TeamTracker sensor.  The state can be PRE (before a game), IN (during a game), or POST (after the game).  If I have multiple cards on the same tab, the first card using variables in the style section will not render correctly.  Additionally, any other cards with the same state as the first card will also not render correctly.  However, cards with a different state will render correctly, even though they also use variables.

If I change the order of the cards on the tab so that a card with a different state is first.  Suddenly, that card (and any other cards with the same state will stop working) and whatever card used to be first magically starts working.

**Comment by vasqued2** [comment] 2024-08-11 12:37
Here is a workaround that takes advantage of card order impacting behavior.  It appears to work for my [Team Tracker card](https://github.com/vasqued2/ha-teamtracker-card).  Given that most cards use the same approach for invalid entities, I suspect it could work for other cards as well. 

1. Create a new Team Tracker card on the same dashboard tab that your other Team Tracker card/cards are on. If they are on multiple dashboard tabs, you must repeat this on each dashboard tab. The new card should contain a single line of YAML.
```
type: custom:teamtracker-card
```
2. This should create a text visual for the card that simply says "Unknown entity:"
3. Move this new card so it is the first one on the dashboard.
4. Refresh the dashboard on the device having problems so the "Unknown entity:" card displays as the first card.
5. All the other cards should magically render correctly once refreshed.
6. OPTIONAL: Once you have confirmed this corrected the problem, if you have `card-mod` installed, you can change the YAML of the first card to hide the card with "Unknown entity:" As long as this card is first on the dashboard tab, the other cards should render correctly even if nothing is displayed.
```
type: custom:teamtracker-card
card_mod:
  style: |
    ha-card {
     display: none;
    }
```

Hopefully this helps others and also helps ID the root cause.

**Comment by Maddin1684** [comment] 2024-08-11 14:27
This workaround doesn’t work with [weather-chart-card](https://github.com/mlamberts78/weather-chart-card)

**Comment by vasqued2** [comment] 2024-08-11 14:47
The problem is `weather-chart-card` has logic that auto-corrects bad YAML.  I was able to get it to work by adding a manual card and pasting the YAML below and immediately saving.  But if I go back in to re-edit the card, it auto-corrects the bad entity in the YAML and the workaround doesn't work any more.

Try pasting this code in and immediately savings before it has a chance to auto-correct it.

```
type: custom:weather-chart-card
entity: bad
forecast:
  precipitation_type: ''
units:
  pressure: ''
  speed: ''
card_mod:
  style: |
    ha-card {
     display: none;
    }
```

The `card-mod` is optional and can only be used if you have [card-mod](https://github.com/thomasloven/lovelace-card-mod) installed.  If you do, it will hide the card with the error while still enabling the other cards to render correctly.

**Comment by Kanecaine** [comment] 2024-08-11 15:25
Thanks @vasqued2 … can confirm the workaround works. At least this is enough:

```yaml
type: custom:weather-chart-card
entity: 'bad'
```

 Copied this in a new card and all weather-chart-cards after this one are beeing rendered fine. Thanks again!

**Comment by PRProd** [comment] 2024-08-11 17:51
@bgoncal ~ Do you need any more diagnostic help from any of us, or are you able to reproduce the issue on your end?

**Comment by bgoncal** [comment] 2024-08-11 17:53
> @bgoncal ~ Do you need any more diagnostic help from any of us, or are you able to reproduce the issue on your end?

I haven't checked those comments yet, I'm not working during the weekend, I'll follow up during this week, the only thing I did till now was to install firemote on my device and it rendered correctly, perhaps it is only in iPad?

**Comment by PRProd** [comment] 2024-08-11 17:57
> perhaps it is only in iPad?

Yes.  From all of the reports/issues I've found in other GitHub repositories, this seems to be ONLY happening on iPad.

**Comment by bgoncal** [comment] 2024-08-11 17:59
> > perhaps it is only in iPad?
> 
> 
> 
> Yes.  From all of the reports/issues I've found in other GitHub repositories, this seems to be ONLY happening on iPad.

Very weird since the code is shared, anyways, I'll have more details to you during the week, enjoy your Sunday ☀️

**Comment by vasqued2** [comment] 2024-08-11 18:46
> I haven't checked those comments yet, I'm not working during the weekend, I'll follow up during this week, the only thing I did till now was to install firemote on my device and it rendered correctly, perhaps it is only in iPad?

I was able to recreate it in Chrome Version 127.0.6533.100 (Official Build) (64-bit) on Windows by changing the User Agent in Developer Tools from 'Use browser default' to 'Chrome - iPad' in the drop down, which was 'Mozilla/5.0 (iPad; CPU OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/127.0.0.0 Mobile/15E148 Safari/604.1'.  

That's where I was able to run some side-by-side comparisons in different tabs under different user agents and confirmed variables were coming into both correctly and the html that should have been generated from the template was the same even though what was actually being rendered was different.  This is also where I was eventually able to figure out that changing the order of the cards changes which cards are impacted.

So far, it seems like the workaround which takes advantage of that fact works for the Firemote card, my Team Tracker card, and the Weather Chart card.  So it looks like pretty consistent behavior across the cards reporting the issue. 

I also did some quick tests with some other User Agents and was able to recreate with some of them, but I can't remember which ones.  That, combined with the fact that it arose when I upgraded to HA 2024.8.0 and saw the problem on multiple iPads w/ different versions of the Apple app makes me think it was introduced with a Front End change in 2024.8.0, and not something w/ the Apple app itself.

Thanks for your help and let me know if you need anything else to help track it down.

**Comment by mjaksn** [comment] 2024-08-11 23:01
I just wanted to mention that I opened https://github.com/home-assistant/iOS/pull/2913, which I believe would resolve these layout issues seen in the iPad companion app. (Sorry, I accidentally included a GitHub keyword (now removed) where I shouldn't have in the PR summary)

**Comment by mjaksn** [comment] 2024-08-12 14:49
Thank you for the feedback, @bgoncal; the PR is closed. I was short-sighted there and appreciate your work investigating the issue with the frontend team.

**Comment by bgoncal** [comment] 2024-08-12 14:51
@mjaksn Thank you for the proactivity 💪

**Comment by piitaya** [comment] 2024-08-13 10:23
I did some tests and it looks like `lit` is not able to replace the variable with the value : 

Source : 
![image](https://github.com/user-attachments/assets/21288bfa-51b0-4dd1-bde2-6b18b2ac3743)

iPad Mini user-agent (no issue) : 
![image](https://github.com/user-attachments/assets/5c1d570a-14af-49a6-abbb-1d2f29a68444)

iPad Air user-agent (issue) : 
![image](https://github.com/user-attachments/assets/0d5dc058-2009-49e6-8c1b-a54592897206)

I will do some additional tests to see if it's caused by the HA update, or a lit-element update, or something else 😅

**Comment by PRProd** [comment] 2024-08-13 15:36
@piitaya ~

Thanks!  For what it's worth, I package lit with Firemote so a lit update could probably be ruled out.  I do it for two reasons: Stability (resilient to lit package updates) and to keep Firemote in line with the Home Assistant value of "local is better."

In case anyone was wondering why Firemote is such a large add-on, 1.1MB of its code contains over 250 brand logos in highly optimized SVG formats.  Why?  TO KEEP IT LOCAL!  😄 

Thank you everyone for your investigations so far!  Hopefully there will be a resolution soon.

-Doug

**Comment by piitaya** [comment] 2024-08-13 16:07
> In my case, configuring a custom user-agent string in Kiosk Pro that matches Safari on a fully updated iPad fixed the layout issues. I also reproduced the layout issue in a previously unaffected browser by intentionally sending an outdated UA string. These observations make me wonder if the problems could be related to [home-assistant/frontend#16506](https://github.com/home-assistant/frontend/pull/16506).

I can confirm it's related to this PR. I made a production build after and before this PR.

iPad Pro and iPad Air now use the legacy built instead of the modern build. iPad Mini still use the modern build as before.

iPad Air user agent : `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15`
iPad Pro user agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15`
iPad Mini user agent `Mozilla/5.0 (iPad; CPU OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1`

 iPad Pro and iPad Air should use modern build. @steverep It is something you can help for?

Also, this problem highlighted another problem, For some reason, `lit` is not able to deal with variables in css template.

**Source** 
```css
:host {
    --sz: ${scale};
    --devicenamecolor: ${devicenamecolor};
    --appButtonFilter: ${AppLaunchButtonFilterCssValue};
}
```

**Generated css by lit (legacy build)**
```css
:host {
    --sz: 1;
    --devicenamecolor: #000000;
    --appButtonFilter: grayscale(0%) brightness(100%);
}
```

**Generated css by lit (modern build)**
```css
:host {
    --sz: lit $ 655874186 $;
    --devicenamecolor: lit $ 655874186 $;
    --appButtonFilter: lit $ 655874186 $;
}
```

**Comment by steverep** [comment] 2024-08-13 16:30
Just to be clear, iOS 17+ should obviously still get the modern build.  This is clearly an upstream bug in https://github.com/browserslist/browserslist-useragent-regexp (or one of its dependencies).  @piitaya or someone else, can you report the issue to them with the problematic user agent strings?  I don't have time to work this now but can dig in later tonight my time.

**Comment by piitaya** [comment] 2024-08-13 16:44
@steverep According to the rule we set, we didn't have iOS 16.0 - 16.5 because it's older than 1 year and less than 0.5%.

https://browsersl.ist/#q=unreleased+versions%0Alast+1+year%0AFirefox+ESR%0A%3E%3D+0.5%25+and+supports+es6-module-dynamic-import%0Anot+dead

I will do some additional tests with a device with Safari 17 to see if I have the same issue.

**Comment by steverep** [comment] 2024-08-13 16:52
> @steverep According to the rule we set, we didn't have iOS 16.0 - 16.5 because it's older than 1 year and less than 0.5%.

Right, but the OP claims this is a problem on 17.6.  Am I not caught up here?  We could certainly revisit the usage threshold, but in this case it seems like we'd only be doing so because there's a bug in the legacy build.

> Also, this problem highlighted another problem, For some reason, lit is not able to deal with variables in css template.

I'd speculate this is probably a bug in the legacy build?


The CSS problem

**Comment by steverep** [comment] 2024-08-13 17:07
And FWIW, 16.6+ should still get the modern build (the usage stats always reflect that most people have updated their devices to the latest supported OS version).

**Comment by piitaya** [comment] 2024-08-13 17:45
I just checked and the user agent is different from the app and the browser.

Here's for my iPad:

Browser: 

Mozilla/5.0 (iPad; CPU OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1

App: 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.7 (io.robbie.HomeAssistant; build:2024.730; iPadOS 17.5.1) Mobile/HomeAssistant, like Safari

**Comment by piitaya** [comment] 2024-08-13 18:19
> I'd speculate this is probably a bug in the legacy build?

Yeah, it's a bug in the legacy build we should fix. I will check if we already had it few releases ago.

**Comment by piitaya** [comment] 2024-08-13 18:32
I just checked and the bug is present for legacy build for more than one year (tested with 2023.7).

**Comment by steverep** [comment] 2024-08-13 18:33
Okay, to level set, it sounds like we've got 2 problems here:

1. The legacy build has a CSS variable issue we need to fix.  We should open a frontend issue for that to keep it separate.
2. The user agent string coming from the apps is being marked as legacy.  My assumption would be that we need to fix that in this repo.  I can dig into that.

As a related aside, the android app also modifies the user agent string.  I don't have a setup to check, but I'll have to check that as well.  If anyone could confirm or deny the legacy build being served on a modern device there, it would help.

**Comment by piitaya** [comment] 2024-08-13 18:54
Exactly! For the user agent modification, the iPhone one works, only the iPad one is broken. I will check with @bgoncal if we can improve that point!

**Comment by steverep** [comment] 2024-08-13 19:15
So it looks like we already have some [custom code in the iOS app to handle some sniffing that CodeMirror does](https://github.com/home-assistant/iOS/blob/f11c496833b70c54ec2b3b5333cfe5bd8f43d12c/Sources/Shared/API/HAAPI.swift#L58).

@bgoncal can you educate me on why we modify the user agent string in the first place for the apps?  I think it's fine to add to it, but in general to avoid any issues with the frontend or any of its dependencies, we should only add to it.  Requests should contain the entire string as set by the webkit web view.

For completeness, here's the [equivalent code in the android app](https://github.com/home-assistant/android/blob/f0a4cd5a6e45ce67c8751538755f80fbc30eda51/common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt#L27).

**Comment by steverep** [comment] 2024-08-13 19:37
BTW, here's the current regex, which does return false for the app string above because it's just too different from what the browser would otherwise send (e.g. incorrectly identifying itself as OSX):


```js
/Edge?\/(1{2}[6-9]|1[2-9]\d|[2-9]\d{2}|\d{4,})\.\d+(\.\d+|)|Firefox\/(1{2}[5-9]|1[2-9]\d|[2-9]\d{2}|\d{4,})\.\d+(\.\d+|)|Chrom(ium|e)\/(109|1[1-9]\d|[2-9]\d{2}|\d{4,})\.\d+(\.\d+|)|(Maci|X1{2}).+ Version\/(17\.\d+|(1[89]|[2-9]\d|\d{3,})\.\d+)([,.]\d+|)( \(\w+\)|)( Mobile\/\w+|) Safari\/|Chrome.+OPR\/(10[2-9]|1[1-9]\d|[2-9]\d{2}|\d{4,})\.\d+\.\d+|(CPU[ +]OS|iPhone[ +]OS|CPU[ +]iPhone|CPU IPhone OS|CPU iPad OS)[ +]+(15[._]([6-9]|\d{2,})|(1[6-9]|[2-9]\d|\d{3,})[._]\d+)([._]\d+|)|Android:?[ /-](1{2}[6-9]|1[2-9]\d|[2-9]\d{2}|\d{4,})(\.\d+|)(\.\d+|)|Mobile Safari.+OPR\/([89]\d|\d{3,})\.\d+\.\d+|Android.+Firefox\/(1{2}[7-9]|1[2-9]\d|[2-9]\d{2}|\d{4,})\.\d+(\.\d+|)|Android.+Chrom(ium|e)\/(1{2}[6-9]|1[2-9]\d|[2-9]\d{2}|\d{4,})\.\d+(\.\d+|)|SamsungBrowser\/(2[3-9]|[3-9]\d|\d{3,})\.\d+/.test(navigator.userAgent)
```

**Comment by steverep** [comment] 2024-08-14 05:47
@piitaya  I'm assuming those strings are from the same device?  What's interesting is that the browser is presenting itself as mobile, but the app webview is presenting itself as desktop.  And the desktop string is missing the pieces that give the version, which can be seen by breaking down the regex:

```js
// Safari (version comes from "Version/<version>" and also needs "Safari/")
/(Maci|X1{2}).+ Version\/(17\.\d+|(1[89]|[2-9]\d|\d{3,})\.\d+)([,.]\d+|)( \(\w+\)|)( Mobile\/\w+|) Safari\//

// iOS (version interpreted from platform part of string)
/(CPU[ +]OS|iPhone[ +]OS|CPU[ +]iPhone|CPU IPhone OS|CPU iPad OS)[ +]+(15[._]([6-9]|\d{2,})|(1[6-9]|[2-9]\d|\d{3,})[._]\d+)([._]\d+|)/
```

Whether or not the webview sends the desktop or mobile version looks to be controlled by [`WKWebpagePreferences`](https://developer.apple.com/documentation/webkit/wkwebpagepreferences).

**Comment by bgoncal** [comment] 2024-08-14 08:23
> So it looks like we already have some [custom code in the iOS app to handle some sniffing that CodeMirror does](https://github.com/home-assistant/iOS/blob/f11c496833b70c54ec2b3b5333cfe5bd8f43d12c/Sources/Shared/API/HAAPI.swift#L58).
> 
> @bgoncal can you educate me on why we modify the user agent string in the first place for the apps? I think it's fine to add to it, but in general to avoid any issues with the frontend or any of its dependencies, we should only add to it. Requests should contain the entire string as set by the webkit web view.
> 
> For completeness, here's the [equivalent code in the android app](https://github.com/home-assistant/android/blob/f0a4cd5a6e45ce67c8751538755f80fbc30eda51/common/src/main/java/io/homeassistant/companion/android/common/data/HomeAssistantApis.kt#L27).

I dont know exactly the background for this change but as you can see in this [PR](https://github.com/home-assistant/iOS/pull/632) we are not overriding the user agent and instead appending to it, so the WKWebView itself presents as macOS on iPad. (More details [here](https://forums.developer.apple.com/forums/thread/122189), as said in this thread, it can be tweaked)

The problem is that even if I fix this for iPad somehow and make it present itself as iPad, our macOS App suffers from the same issue, so we need a fix for it too.

**Comment by bgoncal** [comment] 2024-08-14 08:50
This is a fresh new project with no modification of user agent at all and it is broken as well
![CleanShot 2024-08-14 at 10 49 47@2x](https://github.com/user-attachments/assets/fc0bc5ab-4448-45a1-b3a3-67c5348464b9)

**Comment by bgoncal** [comment] 2024-08-14 09:04
user agent for the sample project above `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"`

**Comment by bgoncal** [comment] 2024-08-14 11:06
This fixes the issue for iPad https://github.com/home-assistant/iOS/pull/2918, but not for macOS App, but I shouldn't have to set this `preferredContentMode`, Apples handle it, if it is an iPad mini it gets mobile websites content mode, if the iPad screen is bigger it gets desktop-class websites, mobile gets "iPad" in user agent, desktop gets "Macintosh".

In my opinion the regex needs to be updated to handle WKWebView and not the otherway around

**Comment by slipx06** [comment] 2024-08-14 17:50
This issue was also reports on Galaxy Tab with Kiosk 6.1.0 and Huawei Matepad 7

**Comment by steverep** [comment] 2024-08-16 03:42
> This issue was also reported to be present on a Galaxy Tab with Kiosk 6.1.0 and Huawei Matepad 7

@slipx06 where is that reported?  What is the user agent string?

**Comment by slipx06** [comment] 2024-08-16 07:26
Hi @steverep. It was reported https://github.com/slipx06/sunsynk-power-flow-card/issues/500#issuecomment-2278593238

@jzielke84 can you confirm the user agent strings

**Comment by slipx06** [comment] 2024-08-16 13:08
Thanks @jzielke84 I can confirm that both those user agents are causing an issue

**Comment by piitaya** [comment] 2024-08-16 14:28
@slipx06, @jzielke84 Those are considered as legacy according to the new rules. Here's the new browser minimal versions to support the modern build : 

| Browser | Legacy | Current Modern | New Modern |
|:---:|:---:|:---:|:---:|
| Android | 60 | 63 | 115 |
| Chrome | 60 | 63 | 109 |
| Edge | 16 | 79 | 115 |
| Firefox | 52 | 67 | 115 |
| iOS | 10.3 | 13 | 15.6 |
| Safari | 11 | 13 | 16.6 |
| Opera | 47 | 50 | 101 |
| Opera Mobile\* | - | 80 | 80 |
| Samsung | 4 | 8.2 | 22 |

But even if it's legacy, all the HA feature should work. We did that change to reduce the bundle size for modern browser.

Also, good news : **I found why these custom card have rendering issue when using legacy build 🎉**
With HA 2024.8, more devices are considered as legacy so this issue wasn't often visible before but was still present.
The legacy build comes with ShadyCSS polyfill to support scoped CSS. One of the limitation is that doesn't support dynamic CSS : (source: https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#dynamically-created-styles-are-not-supported).

I open a [PR on Weather chart card repository](https://github.com/mlamberts78/weather-chart-card/pull/223). Same fix can be used for every custom card that have the same issue.

As a fix, custom card can update their code to static styles and adapt the style using css variables and classes (`classMap` and `styleMap`). I don't think we can fix it on the HA side. The issue is present for year but not really visible because of the modern build versions.

**Comment by jzielke84** [comment] 2024-08-16 14:37
@piitaya Thank you for your research on this one. Maybe this should be published as a breaking change?

**Comment by bgoncal** [comment] 2024-08-16 14:50
I'll be closing the issue in iOS repo since no App change is needed, feel free to keep discussing or move the conversation to frontend if needed.

Thanks @piitaya and @steverep !

**Closed by bgoncal** 2024-08-16 14:50 UTC
Labels: bug, ios

**Comment by steverep** [comment] 2024-08-20 21:13
> As a fix, The custom card code needs to use static styles and adapt the style using css variables and classes (`classMap` and `styleMap`) instead of using dynamic style with template literals. I don't think we can fix it on the HA side.

While making those template changes is definitely the best option, I researched more about what's going on here and there's more we can do.  See https://github.com/home-assistant/frontend/issues/21748, and let's move further discussion there.

> @piitaya Thank you for your research on this one. Maybe this should be published as a breaking change?

This has already been mostly reversed by @bgoncal's change in this repo and https://github.com/home-assistant/frontend/pull/21724 pending in the frontend.  Given we are later in the month now, I'd expect you'd see those in 2024.9.  I can also fix it further on everything but the oldest of old devices (see the frontend issue).
