### ISSUE TITLE
Home Assistant Companion crashes on first run

### ISSUE THREAD

**Issue by snowe2010** [home-assistant/iOS#590] opened 2020-05-22 06:30 UTC
**iOS device model, version and app version**

Model Name: iPhone Xs
Software Version: 13.2.3
App version: Can't give app version as it crashes when we click continue

**Home Assistant Core Version**
0.110.1

**Describe the bug**
Download app straight from App Store, open it, click Continue, screen flashes to a different screen for a split second, then crashes immediately. 

**To Reproduce**
Download the app and run?

**Expected behavior**
No crashing... 

**Screenshots**
![GifMaker_20200522002842702](https://user-images.githubusercontent.com/1534535/82638064-47938680-9bc3-11ea-932e-bb47acde4d7b.gif)

**Comment by SeanPM5** [comment] 2020-05-22 06:34
This is a new issue with 0.110 and will hopefully get sorted out soon, but in the meantime here's the fix: https://companion.home-assistant.io/docs/troubleshooting/faqs#app-crashes-on-set-up

**Comment by TomBrien** [comment] 2020-05-22 06:52
As Sean says the cause of this is known. There is a fix already in the dev version of Home Assistant. You need to specify vales for `internal_url` and `external_url` either through the ui or under `homeassistant:` in `configuration.yaml`. Please let us know if this fixes your issue

**Comment by snowe2010** [comment] 2020-05-22 16:42
I still get the issue even though my internal and external url values are filled out. Do they need to be a specific format? All I did was copy the internal to the external (as I have nabu casa and will need to set the external up later after setup)
![image](https://user-images.githubusercontent.com/1534535/82690121-e3031680-9c18-11ea-928d-6e657d7d14b5.png)

**Comment by snowe2010** [comment] 2020-05-23 00:23
Tried with the nabu casa url with no luck. No clue what values I should be setting here, as our system is Nabu Casa and the app sets that all automatically based on the internal ip.

**Comment by TomBrien** [comment] 2020-05-23 06:08
@snowe2010 do you have `http` set somewhere? I’d suggest commenting that out temporally if you do. Do you have Remote Control turned on in the Home Assistant Cloud settings?

**Comment by TomBrien** [comment] 2020-05-23 06:26
Also, most importantly, did you restart Home Assistant after adding `external_url` and `internal_url`?

**Comment by gsubiran** [comment] 2020-05-23 12:59
I faced the same issue. My workaround was turn off WiFi on phone and setup first time the app with mobile data (obviously you need to have configured to external connection). Then just enabling again WiFi and app didn’t being crashing.

Guillermo Subirán
________________________________

**Comment by TomBrien** [comment] 2020-05-23 13:18
Yep that should get you around the crash. However, I think doing that will not allow the app to know your home wifi SSID and may be a problem for people with hairpin NAT issues

**Comment by TomBrien** [comment] 2020-05-23 13:18
@snowe2010 Can you let me know if you have got past the crash now?

**Comment by nolenjohan** [comment] 2020-05-23 14:15
I followed suggestion from @gsubiran  above, connected while disabled WiFi, after re-activating WiFi it still works fine. I have the same https addresses for both Internal as External.

**Comment by snowe2010** [comment] 2020-05-23 20:26
I think the issue was restarting HA, but am not sure. It appears to be working now though! Was able to start up and connect and it detected nabu casa correctly and everything appears to be working.

**Comment by TomBrien** [comment] 2020-06-05 22:09
This is fixed via home-assistant/core#36490 which is being released as a quick fix right now

**Closed by TomBrien** 2020-06-05 22:09 UTC
Labels: bug, crash
