### ISSUE TITLE
Back button not functioning in HACS integrations

### ISSUE THREAD

**Issue by alsoszaa** [home-assistant/iOS#2322] opened 2023-03-18 01:49 UTC
**iOS device model, version and app version**

Model Name: iPhone 14 pro max
Software Version: iOS 16.3.1 (20D67)
App version: not sure since I'm stuck (iOS app version)

**Home Assistant Core Version**

2023.3.4

**Describe the bug**

I have the latest iPhone App for home assistant, the latest home assistant version and the latest HACS version. But I went into one of the integrations in HACS to see if I was interested in installing it. The issue now is that the back button out of this integration doesn’t work. So now I am stuck in this page. Closing the app and reopening it takes me to the same HACS integration page and I’m still stuck. This is definitely a bug, just not sure where to report it. All I can do now is uninstall the home assistant app from my phone and reinstall. But then do I need to do this each time I want to see details of a cool integration in HACS?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by alsoszaa** [comment] 2023-03-18 01:52
Specifically this is the SpaceX integration I was looking at and am now stuck. Swiping left or right was the advice in the home assistant discord app, but this did nothing.

**Comment by Boardron** [comment] 2023-03-19 16:43
Experience the same issue but I have some further insights:

**Insight**
It seems that the app DOES store the last page visited, but it DOESN'T store the page history. It's my guess that since the back button (in subview) uses the history and there isn't one, the back button has nothing to do.

**Workaround**
Go to "Edit Dahsboard" => "Manage Dashboard" and you're good to go again aka "unstuck".

**Possible Solution**
Well IF the back button is activated AND the history is empty THEN goto the default dashboard for that user?

**Comment by dmelliott20** [comment] 2023-04-16 19:49
Yep I’ve managed to get stuck on a HACS integration page. Rebooting the phone doesn’t even work.

**Comment by FelisucoVFR** [comment] 2023-12-26 10:29
I had the same issue a few times with different integrations.
iPhone 13

**Comment by markwoitaszek** [comment] 2024-02-13 02:14
I encountered the same problem and was able to devise a quick workaround. To resolve, close the application, then reopen. On load, you will notice the orange gear app settings icon momentarily appears in the lower right corner of the screen. If you act quickly, you can access the settings before the icon vanishes. Proceed to remove and re-add the server. This forces the configuration to reset and will then load the default dashboard.

**Comment by pgale** [comment] 2024-02-18 14:58
I've seen the same issue when browsing integrations (Sonos card and one other I can't remember). In my case, I had left the companion app for some time and when I came back, the back button wasn't working. Maybe there should also be a home button if possible - that would make sense anyway. I had to reinstall the app to get it back to the home screen.

Thanks to @markwoitaszek - that worked for me as a temp fix :)

Easy to reproduce - go into HACS, tap on an installed integration, close the app, open the app - opens the integration info screen and the back button is broken (probably no history as others have mentioned) 

Is this a HACS issue or an iOS companion app issue? I've seen others report similar behaviour on the back button but in different screens (add-on) - they still seem to be open issues so not sure if anyone is looking at fixing this?

**Comment by segdy** [comment] 2024-08-20 02:52
I am just facing the same issue, over a year later.

i also tried reset front end cache without success

**Comment by pgale** [comment] 2024-08-20 05:36
I still see this occasionally too.

**Comment by bgoncal** [comment] 2024-12-13 21:29
@Crazyscorpio88 the back button is controlled by the frontend and not the app itself, probably thats why it wasnt reported any fix here, consider opening an issue to frontend instead.

Because of the above ill be closing the issue here, feel free to reference it when you open an issue to frontend.

**Closed by bgoncal** 2024-12-13 21:29 UTC
Labels: bug, ios
